import { defineConfig } from 'oxlint';

export default defineConfig({
	plugins: ['typescript', 'react', 'vitest', 'jsx-a11y', 'import', 'promise', 'node'],
	env: {
		browser: true,
		node: true,
		es6: true,
	},
	ignorePatterns: [
		'node_modules/**',
		'dist/**',
		'build/**',
		'coverage/**',
		'out/**',
		'.vercel/**',
		'.cache/**',
		'.image-cache/**',
		'.thumbnail-cache/**',
		'public/assets/**',
		'.env',
		'.env.*',
		'*.log',
		'*.lock',
		'*.d.ts',
		'*.tsbuildinfo',
		'*.sqlite',
		'*.sqlite3',
		'*.sqlite-journal',
		'.vscode/**',
		'src/components/features/file-browser/file-browser-backup.tsx',
		'**/*.backup.*',
	],
	settings: {
		react: {
			version: '19.2.4',
		},
		vitest: {
			typecheck: false,
		},
	},
	rules: {
		'no-console': 'off',
		'no-debugger': 'error',
		'no-unused-vars': 'off',
		eqeqeq: 'off',
		'no-unused-expressions': 'off',
		'no-control-regex': 'off',
		'require-yield': 'off',
		'react/react-in-jsx-scope': 'off',
		'react/jsx-uses-react': 'off',
		'react/prop-types': 'off',
		'react/no-unescaped-entities': 'off',
		'react-hooks/exhaustive-deps': 'off',
		'jsx-a11y/alt-text': 'off',
		'jsx-a11y/anchor-has-content': 'off',
		'jsx-a11y/click-events-have-key-events': 'off',
		'jsx-a11y/heading-has-content': 'off',
		'jsx-a11y/media-has-caption': 'off',
		'jsx-a11y/no-autofocus': 'off',
		'jsx-a11y/no-static-element-interactions': 'off',
		'jsx-a11y/prefer-tag-over-role': 'off',
		'@typescript-eslint/no-explicit-any': 'off',
		'@typescript-eslint/no-non-null-assertion': 'off',
		'@typescript-eslint/explicit-module-boundary-types': 'off',
		'@typescript-eslint/no-empty-interface': 'off',
		'import/no-cycle': 'off',
		'import/namespace': 'off',
		'jest/expect-expect': 'off',
		'jest/no-conditional-expect': 'off',
		'jest/require-to-throw-message': 'off',
		'promise/prefer-await-to-then': 'off',
	},
});