import type { PrismaClient } from '@prisma/client';
import { seedLogger, tableExists } from './utils.seed';

/**
 * Siembra los lugares por defecto en la base de datos
 * @param prisma Cliente de Prisma
 */
export async function seedPlaces(prisma: PrismaClient): Promise<void> {
  seedLogger.info('📍 Creando lugares por defecto...');

  // Verificar si la tabla Place existe
  if (await tableExists(prisma, 'Place')) {
    // Crear lugares por defecto
    await prisma.place.createMany({
      data: [
        {
          name: 'Ciudad Capital',
          emoji: '🏙️',
          color: '#3b82f6',
          description: 'La gran metrópolis central, centro de comercio y política',
          shortcut: 'capital',
          category: 'urbano',
          sortBy: 'name',
          filters: JSON.stringify(['type:city']),
          region: 'central',
          type: 'city',
          climate: 'temperate',
          population: 500000,
          government: 'monarchy',
          dangers: JSON.stringify(['Gremio de ladrones', 'Corrupción política', 'Epidemias ocasionales']),
          resources: JSON.stringify(['Comercio', 'Artesanía', 'Conocimiento']),
          lore: 'Fundada hace mil años tras la Gran Guerra, ha sido el centro del reino desde entonces.',
          history: 'Sobrevivió a tres asedios importantes y dos incendios devastadores a lo largo de su historia.',
          stats: JSON.stringify({
            defensa: 18,
            economía: 20,
            cultura: 16,
            criminalidad: 14
          }),
          featuredImage: null,
          isFavorite: true,
        },
        {
          name: 'Bosque Profundo',
          emoji: '🌲',
          color: '#10b981',
          description: 'Un antiguo bosque lleno de misterios y criaturas extrañas',
          shortcut: 'forest',
          category: 'natural',
          sortBy: 'name',
          filters: JSON.stringify(['type:forest']),
          region: 'northern',
          type: 'forest',
          climate: 'temperate',
          population: 500,
          government: 'tribal',
          dangers: JSON.stringify(['Bestias salvajes', 'Tribus hostiles', 'Plantas venenosas', 'Magia salvaje']),
          resources: JSON.stringify(['Madera rara', 'Hierbas medicinales', 'Cristales mágicos']),
          lore: 'Se dice que el bosque está vivo y consciente, y que los árboles más antiguos pueden hablar con aquellos de corazón puro.',
          history: 'Existente desde antes de la llegada de los humanos, ha sido testigo del ascenso y caída de muchas civilizaciones.',
          stats: JSON.stringify({
            magia: 19,
            peligro: 15,
            recursos: 17,
            misterio: 20
          }),
          featuredImage: null,
          isFavorite: false,
        },
        {
          name: 'Montañas Nebulosas',
          emoji: '🏔️',
          color: '#6b7280',
          description: 'Imponente cordillera cubierta por niebla perpetua',
          shortcut: 'mount',
          category: 'natural',
          sortBy: 'name',
          filters: JSON.stringify(['type:mountains']),
          region: 'eastern',
          type: 'mountains',
          climate: 'cold',
          population: 2000,
          government: 'clan',
          dangers: JSON.stringify(['Avalanchas', 'Criaturas de las alturas', 'Frío extremo', 'Bandidos']),
          resources: JSON.stringify(['Minerales preciosos', 'Cristales de poder', 'Hierbas raras']),
          lore: 'Las cumbres más altas están perpetuamente cubiertas por una niebla mágica que se dice oculta el hogar de los dioses.',
          history: 'Antiguo hogar de los enanos, quienes construyeron vastas ciudades subterráneas que ahora yacen abandonadas.',
          stats: JSON.stringify({
            altitud: 20,
            recursos: 18,
            accesibilidad: 7,
            misterio: 16
          }),
          featuredImage: null,
          isFavorite: false,
        },
        {
          name: 'Puerto Comercial',
          emoji: '⚓',
          color: '#0ea5e9',
          description: 'Bullicioso puerto que conecta reinos a través del mar',
          shortcut: 'port',
          category: 'urbano',
          sortBy: 'name',
          filters: JSON.stringify(['type:port']),
          region: 'coastal',
          type: 'port',
          climate: 'tropical',
          population: 120000,
          government: 'merchant council',
          dangers: JSON.stringify(['Piratas', 'Contrabandistas', 'Enfermedades exóticas']),
          resources: JSON.stringify(['Comercio marítimo', 'Pescado', 'Bienes exóticos']),
          lore: 'Se dice que bajo el puerto existe una ciudad sumergida de una antigua civilización avanzada.',
          history: 'Comenzó como un pequeño pueblo pesquero hace 500 años, pero creció exponencialmente al convertirse en centro de comercio.',
          stats: JSON.stringify({
            comercio: 20,
            defensa: 12,
            cultura: 15,
            influencia: 18
          }),
          featuredImage: null,
          isFavorite: false,
        },
        {
          name: 'Desierto de las Almas',
          emoji: '🏜️',
          color: '#f59e0b',
          description: 'Vasto desierto inhóspito con ruinas antiguas y secretos enterrados',
          shortcut: 'desert',
          category: 'natural',
          sortBy: 'name',
          filters: JSON.stringify(['type:desert']),
          region: 'southern',
          type: 'desert',
          climate: 'arid',
          population: 100,
          government: 'nomadic',
          dangers: JSON.stringify(['Tormentas de arena', 'Escorpiones gigantes', 'Deshidratación', 'Espejismos mágicos']),
          resources: JSON.stringify(['Reliquias antiguas', 'Cristales solares', 'Plantas desérticas raras']),
          lore: 'El desierto fue creado hace milenios cuando un imperio arrogante desafió a los dioses y fue castigado.',
          history: 'Bajo las arenas yacen docenas de ciudades antiguas, con tesoros y peligros en igual medida.',
          stats: JSON.stringify({
            hostilidad: 19,
            tesoros: 16,
            misterio: 18,
            magia: 15
          }),
          featuredImage: null,
          isFavorite: false,
        },
        {
          name: 'El Abismo',
          emoji: '🕳️',
          color: '#1e293b',
          description: 'Una grieta dimensional donde las fuerzas oscuras distorsionan la realidad',
          shortcut: 'abismo',
          category: 'dimensional',
          sortBy: 'name',
          filters: JSON.stringify(['type:void']),
          region: 'void',
          type: 'dimensional rift',
          climate: 'otherworldly',
          population: 0,
          government: 'chaos',
          dangers: JSON.stringify(['Entidades del vacío', 'Corrupción mental', 'Distorsiones espaciales']),
          resources: JSON.stringify(['Cristales del vacío', 'Esencia oscura', 'Reliquias corrompidas']),
          lore: 'Un lugar donde la realidad se dobla y las pesadillas cobran vida. Kael el Caminante del Abismo quedó marcado por este lugar.',
          history: 'Apareció hace siglos cuando un ritual fallido rasgó el tejido de la realidad.',
          stats: JSON.stringify({
            corrupción: 20,
            peligro: 19,
            magia: 18,
            misterio: 20
          }),
          featuredImage: null,
          isFavorite: false,
        },
        {
          name: 'Tierras del Norte Helado',
          emoji: '❄️',
          color: '#f1f5f9',
          description: 'Reino congelado donde solo los más fuertes sobreviven',
          shortcut: 'norte',
          category: 'natural',
          sortBy: 'name',
          filters: JSON.stringify(['type:tundra']),
          region: 'far north',
          type: 'tundra',
          climate: 'arctic',
          population: 5000,
          government: 'tribal council',
          dangers: JSON.stringify(['Tormentas de hielo', 'Bestias del hielo', 'Congelación']),
          resources: JSON.stringify(['Hierro helado', 'Pieles', 'Cristales de hielo']),
          lore: 'Tierra natal de Isolda la Nacida del Hielo, donde el frío forja guerreros legendarios.',
          history: 'Durante milenios, las tribus del norte han resistido intentos de conquista gracias a su ferocidad y al clima inclemente.',
          stats: JSON.stringify({
            supervivencia: 18,
            combate: 16,
            resistencia: 19,
            tradición: 15
          }),
          featuredImage: null,
          isFavorite: false,
        },
        {
          name: 'Bosque Primordial',
          emoji: '🌳',
          color: '#166534',
          description: 'El corazón verde del mundo, donde la naturaleza reina suprema',
          shortcut: 'primordial',
          category: 'natural',
          sortBy: 'name',
          filters: JSON.stringify(['type:ancient forest']),
          region: 'central',
          type: 'ancient forest',
          climate: 'temperate',
          population: 1000,
          government: 'druidic circle',
          dangers: JSON.stringify(['Plantas carnívoras', 'Espíritus antiguos', 'Trampas naturales']),
          resources: JSON.stringify(['Hierbas sagradas', 'Madera viviente', 'Frutos mágicos']),
          lore: 'Protegido por Garruk el Salvaje y el Círculo de Druidas, este bosque es el último bastión de la magia natural pura.',
          history: 'El bosque existe desde antes que la primera civilización y ha resistido todos los intentos de domesticación.',
          stats: JSON.stringify({
            naturaleza: 20,
            magia: 17,
            antigüedad: 19,
            pureza: 18
          }),
          featuredImage: null,
          isFavorite: false,
        },
        {
          name: 'Biblioteca Prohibida',
          emoji: '📚',
          color: '#7c3aed',
          description: 'Repositorio de conocimientos oscuros y saberes prohibidos',
          shortcut: 'biblioteca',
          category: 'estructura',
          sortBy: 'name',
          filters: JSON.stringify(['type:library']),
          region: 'unknown',
          type: 'magical structure',
          climate: 'controlled',
          population: 50,
          government: 'arcane council',
          dangers: JSON.stringify(['Libros malditos', 'Guardianes espectrales', 'Conocimiento corrupto']),
          resources: JSON.stringify(['Grimorios antiguos', 'Pergaminos prohibidos', 'Artefactos arcanos']),
          lore: 'Lugar de estudio de Eryndor el Eterno, donde los secretos más oscuros son custodiados.',
          history: 'Construida por hechiceros antiguos para preservar conocimientos demasiado peligrosos para el mundo.',
          stats: JSON.stringify({
            conocimiento: 20,
            peligro: 17,
            secretos: 19,
            protección: 18
          }),
          featuredImage: null,
          isFavorite: false,
        },
        {
          name: 'Templo Caído',
          emoji: '🏛️',
          color: '#cbd5e1',
          description: 'Ruinas sagradas de una orden antigua, ahora abandonadas',
          shortcut: 'templo',
          category: 'ruinas',
          sortBy: 'name',
          filters: JSON.stringify(['type:temple']),
          region: 'eastern',
          type: 'ruins',
          climate: 'temperate',
          population: 0,
          government: 'abandoned',
          dangers: JSON.stringify(['Trampas antiguas', 'Fantasmas inquietos', 'Sectarios']),
          resources: JSON.stringify(['Reliquias sagradas', 'Textos antiguos', 'Artefactos benditos']),
          lore: 'Antiguo hogar de la orden de Serafina la Caída, ahora un recordatorio de gloria perdida.',
          history: 'Una vez fue el centro de una poderosa orden religiosa hasta que un evento misterioso causó su caída.',
          stats: JSON.stringify({
            sacralidad: 16,
            ruina: 15,
            historia: 18,
            misterio: 17
          }),
          featuredImage: null,
          isFavorite: false,
        },
        {
          name: 'Ruinas Malditas',
          emoji: '🏚️',
          color: '#475569',
          description: 'Vestigios de una civilización antigua consumida por la maldición',
          shortcut: 'ruinas',
          category: 'ruinas',
          sortBy: 'name',
          filters: JSON.stringify(['type:cursed ruins']),
          region: 'wasteland',
          type: 'cursed ruins',
          climate: 'dead',
          population: 0,
          government: 'none',
          dangers: JSON.stringify(['Maldición antigua', 'No muertos', 'Corrupción']),
          resources: JSON.stringify(['Reliquias malditas', 'Esencia oscura', 'Metales corroídos']),
          lore: 'Hogar actual de Aldric el Hueco, estas ruinas son testigo de una tragedia antigua.',
          history: 'Una próspera ciudad hasta que una maldición consumió a todos sus habitantes.',
          stats: JSON.stringify({
            maldición: 20,
            desolación: 18,
            peligro: 17,
            muerte: 19
          }),
          featuredImage: null,
          isFavorite: false,
        }
      ],
    });
    seedLogger.info('✅ Lugares creados correctamente');
  } else {
    seedLogger.warn('⚠️ La tabla Place no existe, omitiendo...');
  }
}