import type { LayerImplementation } from '../types';
import { PRESET_COLORS, type ScanlinesConfig } from './actions/scanlines-config.action';
import { ScanlinesLayer } from './components/scanlines-layer';
import { ScanlinesSettings } from './components/scanlines-settings';

/**
 * 📺 Implementación de la capa de líneas de escaneo
 * @module ScanlinesLayer
 */
export const scanlinesImplementation: LayerImplementation<ScanlinesConfig> = {
	type: 'scanlines',
	name: 'Líneas de escaneo',
	description: 'Añade un efecto de líneas de escaneo retro',
	icon: '📺',
	defaultConfig: {
		enabled: true,
		visibleOnHover: false,
		layerIndex: 3,
		opacity: 0.15,
		lineWidth: 1,
		lineSpacing: 3,
		speed: 0,
		color: PRESET_COLORS.BLACK,
		blendMode: 'multiply',
		direction: 'horizontal',
		animated: false,
		offset: 0,
	},
	render: ScanlinesLayer,
	settings: ScanlinesSettings,
	presets: [
		{
			name: 'TV Retro',
			description: 'Efecto de televisión antigua con líneas horizontales',
			config: {
				enabled: true,
				visibleOnHover: false,
				layerIndex: 3,
				opacity: 0.15,
				lineWidth: 1,
				lineSpacing: 3,
				speed: 0,
				color: PRESET_COLORS.BLACK,
				blendMode: 'multiply',
				direction: 'horizontal',
				animated: false,
				offset: 0,
			},
		},
		{
			name: 'Monitor CRT',
			description: 'Efecto de monitor CRT con líneas verticales',
			config: {
				enabled: true,
				visibleOnHover: false,
				layerIndex: 3,
				opacity: 0.2,
				lineWidth: 1.5,
				lineSpacing: 4,
				speed: 0,
				color: PRESET_COLORS.WHITE,
				blendMode: 'soft-light',
				direction: 'vertical',
				animated: false,
				offset: 0,
			},
		},
		{
			name: 'Cyberpunk',
			description: 'Efecto futurista con líneas animadas',
			config: {
				enabled: true,
				visibleOnHover: false,
				layerIndex: 3,
				opacity: 0.25,
				lineWidth: 2,
				lineSpacing: 6,
				speed: 2,
				color: PRESET_COLORS.CYAN,
				blendMode: 'screen',
				direction: 'horizontal',
				animated: true,
				offset: 0,
			},
		},
		{
			name: 'Matrix',
			description: 'Efecto Matrix con líneas verdes',
			config: {
				enabled: true,
				visibleOnHover: false,
				layerIndex: 3,
				opacity: 0.2,
				lineWidth: 1,
				lineSpacing: 2,
				speed: 5,
				color: PRESET_COLORS.GREEN,
				blendMode: 'screen',
				direction: 'vertical',
				animated: true,
				offset: 0,
			},
		},
		{
			name: 'Glitch',
			description: 'Efecto de glitch con líneas rápidas',
			config: {
				enabled: true,
				visibleOnHover: false,
				layerIndex: 3,
				opacity: 0.3,
				lineWidth: 3,
				lineSpacing: 8,
				speed: 8,
				color: PRESET_COLORS.MAGENTA,
				blendMode: 'exclusion',
				direction: 'horizontal',
				animated: true,
				offset: 0,
			},
		},
	],
};