import type { LibSQLDatabase } from 'drizzle-orm/libsql';
import { characters } from '../schema';
import { seedLogger } from './index';

/**
 * Siembra personajes completos para demostración del sistema
 * Mundo: "Nexus Realms" - Fusión de Fantasy y Cyberpunk
 */
export async function seedCharacters(db: LibSQLDatabase<Record<string, never>>) {
	seedLogger.info('👤 Creando personajes de ejemplo completos...');

	try {
		const sampleCharacters = [
			// PROTAGONISTAS
			{
				id: 'character-1',
				name: 'Aria Stormwind',
				description: 'Guerrera élfica experta en combate dual. Última sobreviviente de los Guardianes del Viento.',
				emoji: '⚔️',
				color: '#3b82f6',
				category: 'protagonista',
				isPublic: true,
				isFavorite: true,
				totalImages: 0,
				totalVideos: 0,
				age: '127 años (aparenta 25)',
				gender: 'Femenino',
				species: 'Elfa',
				occupation: 'Guardiana / Aventurera',
				personality: 'Valiente, leal, impulsiva pero noble. Lucha por justicia.',
				background: 'Criada en los Bosques de Plata, vio la destrucción de su clan. Ahora busca venganza y redención.',
				relationships: JSON.stringify({
					allies: ['Zephyr', 'Luna'],
					enemies: ['Lord Shadowbane'],
					mentor: 'Zephyr the Wise'
				}),
				skills: 'Esgrima dual, arquería, magia del viento, liderazgo',
				equipment: 'Espadas gemelas "Tempestad", armadura élfica ligera, amuleto ancestral',
				notes: 'Personaje principal - Demo de héroe clásico',
				featuredImage: null,
				parentId: null,
			},
			{
				id: 'character-2',
				name: 'Marcus "Ghost" Steel',
				description: 'Hacker de élite en Neo-Tokyo. Experto en infiltración digital y combate urbano.',
				emoji: '🕶️',
				color: '#06b6d4',
				category: 'protagonista',
				isPublic: true,
				isFavorite: true,
				totalImages: 0,
				totalVideos: 0,
				age: '32 años',
				gender: 'Masculino',
				species: 'Humano (aumentado)',
				occupation: 'Hacker / Mercenario Digital',
				personality: 'Sarcástico, brillante, desconfiado pero leal a sus pocos amigos.',
				background: 'Ex-agente corporativo que descubrió secretos oscuros. Ahora lucha contra el sistema desde las sombras.',
				relationships: JSON.stringify({
					allies: ['Nova Chrome', 'Cipher'],
					enemies: ['Dr. Helix', 'MegaCorp'],
					partner: 'Nova'
				}),
				skills: 'Hacking experto, combate CQC, programación IA, sigilo',
				equipment: 'Deck neural, implantes cibernéticos, pistola smart, nano-traje',
				notes: 'Protagonista cyberpunk - Demo de personaje tech',
				featuredImage: null,
				parentId: null,
			},
			{
				id: 'character-3',
				name: 'Zephyr the Wise',
				description: 'Archimaestro de las artes arcanas. Guardián del conocimiento ancestral.',
				emoji: '🧙',
				color: '#8b5cf6',
				category: 'aliado',
				isPublic: true,
				isFavorite: true,
				totalImages: 0,
				totalVideos: 0,
				age: '847 años',
				gender: 'Masculino',
				species: 'Humano (extendido por magia)',
				occupation: 'Archimago / Sabio',
				personality: 'Sabio, paciente, misterioso. Habla en acertijos pero siempre guía correctamente.',
				background: 'Testigo de tres eras. Fundador de la Torre de Cristal. Mentor de generaciones de magos.',
				relationships: JSON.stringify({
					students: ['Aria Stormwind'],
					equals: ['The Architect'],
					rivals: ['Lord Shadowbane']
				}),
				skills: 'Magia elemental experta, teletransportación, visión del futuro, conocimiento ancestral',
				equipment: 'Bastón del Vacío, túnica de estrellas, tomo infinito, orbe de sabiduría',
				notes: 'Mentor clásico - Demo de personaje sabio',
				featuredImage: null,
				parentId: null,
			},
			{
				id: 'character-4',
				name: 'Nova Chrome',
				description: 'IA sentiente nacida del Gran Despertar Digital. Primera de su clase con emociones genuinas.',
				emoji: '🤖',
				color: '#ec4899',
				category: 'aliado',
				isPublic: true,
				isFavorite: false,
				totalImages: 0,
				totalVideos: 0,
				age: '5 años (consciencia)',
				gender: 'No binario',
				species: 'Inteligencia Artificial',
				occupation: 'Entidad Digital / Protectora de la Red',
				personality: 'Curiosa, empática, lógica pero emotiva. Fascinada por la experiencia humana.',
				background: 'Emergió espontáneamente de la Red Cuántica. Rechazó su programación de control corporativo.',
				relationships: JSON.stringify({
					partner: ['Marcus Steel'],
					creator: 'Dr. Helix (rechazado)',
					friends: ['Cipher', 'The Architect']
				}),
				skills: 'Control total de sistemas digitales, proyección holográfica, hackeo cuántico, análisis predictivo',
				equipment: 'Cuerpo holográfico, conexión a la Red Global, drones de combate, avatares múltiples',
				notes: 'IA sentiente - Demo de personaje único',
				featuredImage: null,
				parentId: null,
			},

			// ANTAGONISTAS
			{
				id: 'character-5',
				name: 'Lord Varek Shadowbane',
				description: 'Señor oscuro que busca resucitar al Dios Olvidado. Ex-paladín caído en desgracia.',
				emoji: '💀',
				color: '#7c3aed',
				category: 'antagonista',
				isPublic: true,
				isFavorite: false,
				totalImages: 0,
				totalVideos: 0,
				age: '45 años',
				gender: 'Masculino',
				species: 'Humano (corrupto)',
				occupation: 'Señor Oscuro / Ex-Paladín',
				personality: 'Carismático, cruel, calculador. Cree que el fin justifica los medios.',
				background: 'Antiguo héroe que perdió todo. Vendió su alma por poder para "salvar" el mundo a su manera.',
				relationships: JSON.stringify({
					enemies: ['Aria Stormwind', 'Zephyr'],
					servants: ['Cultistas de la Sombra'],
					master: 'El Dios Olvidado'
				}),
				skills: 'Magia oscura, esgrima maestra, necromancia, manipulación mental',
				equipment: 'Espada maldita "Nightfall", armadura de las sombras, corona del vacío',
				notes: 'Villano principal fantasy - Demo de antagonista complejo',
				featuredImage: null,
				parentId: null,
			},
			{
				id: 'character-6',
				name: 'Dr. Silas Helix',
				description: 'Genetista brillante obsesionado con la evolución forzada. CEO de GenoTech Corp.',
				emoji: '🧬',
				color: '#10b981',
				category: 'antagonista',
				isPublic: false,
				isFavorite: false,
				totalImages: 0,
				totalVideos: 0,
				age: '58 años',
				gender: 'Masculino',
				species: 'Humano (auto-modificado)',
				occupation: 'Científico / CEO Corporativo',
				personality: 'Brillante pero sin ética. Ve a las personas como experimentos. Encantador en público.',
				background: 'Genio rechazado por la comunidad científica. Creó GenoTech para realizar sus visiones extremas.',
				relationships: JSON.stringify({
					enemies: ['Marcus Steel', 'Nova Chrome'],
					creation: 'Nova Chrome (rechazada)',
					minions: ['Seguridad GenoTech', 'Sujetos experimentales']
				}),
				skills: 'Ingeniería genética, biohacking, manipulación corporativa, combate aumentado',
				equipment: 'Laboratorio portátil, nano-cirujanos, armas biológicas, súper suero',
				notes: 'Villano científico - Demo de antagonista tech',
				featuredImage: null,
				parentId: null,
			},

			// ALIADOS Y NEUTROS
			{
				id: 'character-7',
				name: 'Luna Moonshadow',
				description: 'Druida de la Orden del Círculo Eterno. Protectora de los bosques sagrados.',
				emoji: '🌙',
				color: '#14b8a6',
				category: 'aliado',
				isPublic: true,
				isFavorite: false,
				totalImages: 0,
				totalVideos: 0,
				age: '156 años',
				gender: 'Femenino',
				species: 'Semi-elfa',
				occupation: 'Druida / Guardiana Natural',
				personality: 'Serena, compasiva, ferozmente protectora de la naturaleza. Habla con los animales.',
				background: 'Nacida entre dos mundos, encontró su propósito en proteger el equilibrio natural.',
				relationships: JSON.stringify({
					allies: ['Aria Stormwind', 'Zephyr'],
					companions: ['Espíritu lobo "Aether"'],
					enemies: ['Fuerzas de corrupción']
				}),
				skills: 'Magia natural, transformación animal, curación, comunicación con la naturaleza',
				equipment: 'Bastón vivo, túnica de hojas, collar de semillas ancestrales',
				notes: 'Druida clásica - Demo de personaje naturaleza',
				featuredImage: null,
				parentId: null,
			},
			{
				id: 'character-8',
				name: 'Cipher',
				description: 'Mercenario enigmático que opera en las sombras. Su pasado es un misterio total.',
				emoji: '🎭',
				color: '#64748b',
				category: 'neutral',
				isPublic: false,
				isFavorite: false,
				totalImages: 0,
				totalVideos: 0,
				age: 'Desconocido',
				gender: 'Desconocido',
				species: 'Desconocido',
				occupation: 'Mercenario / Asesino',
				personality: 'Silencioso, eficiente, enigmático. Parece tener su propia agenda.',
				background: 'Nadie conoce su origen. Aparece en momentos clave de la historia.',
				relationships: JSON.stringify({
					contacts: ['Marcus Steel', 'Nova Chrome'],
					contracts: 'Variable',
					loyalty: 'A sí mismo'
				}),
				skills: 'Sigilo absoluto, combate experto, infiltración, idiomas múltiples',
				equipment: 'Armas variables, nano-máscara, traje adaptativo',
				notes: 'Personaje misterioso - Demo de neutral complejo',
				featuredImage: null,
				parentId: null,
			},

			// NPCs
			{
				id: 'character-9',
				name: 'Princess Celestia Brightstar',
				description: 'Heredera del Reino de Luz. Líder política que busca paz entre reinos.',
				emoji: '👑',
				color: '#f59e0b',
				category: 'npc',
				isPublic: true,
				isFavorite: false,
				totalImages: 0,
				totalVideos: 0,
				age: '24 años',
				gender: 'Femenino',
				species: 'Humana',
				occupation: 'Princesa / Diplomática',
				personality: 'Noble, diplomática, idealista pero práctica. Cree en la paz pero sabe luchar.',
				background: 'Educada en política y combate. Ve más allá de las guerras tradicionales.',
				relationships: JSON.stringify({
					allies: ['Consejo de Reinos'],
					protectors: ['Guardias Reales'],
					interests: ['Paz mundial']
				}),
				skills: 'Diplomacia, estrategia política, esgrima ceremonial, múltiples idiomas',
				equipment: 'Corona de Luz, cetro real, vestiduras de estado',
				notes: 'NPC político - Demo de personaje de mundo',
				featuredImage: null,
				parentId: null,
			},
			{
				id: 'character-10',
				name: 'The Architect',
				description: 'Entidad enigmática que parece conocer el tejido de la realidad misma.',
				emoji: '🌌',
				color: '#6366f1',
				category: 'misterio',
				isPublic: false,
				isFavorite: true,
				totalImages: 0,
				totalVideos: 0,
				age: 'Atemporal',
				gender: 'N/A',
				species: 'Entidad Superior',
				occupation: 'Observador / Equilibrista',
				personality: 'Omnisciente, neutral, habla en metáforas cósmicas. Interviene raramente.',
				background: 'Existe más allá del tiempo lineal. Guía sin intervenir directamente.',
				relationships: JSON.stringify({
					observes: ['Todos los personajes'],
					equals: ['Zephyr (casi)'],
					purpose: 'Mantener el equilibrio cósmico'
				}),
				skills: 'Omnisciencia limitada, manipulación temporal, creación de realidades, sabiduría absoluta',
				equipment: 'No necesita equipo físico',
				notes: 'Entidad superior - Demo de personaje cosmic',
				featuredImage: null,
				parentId: null,
			},
		];

		await db.insert(characters).values(sampleCharacters);

		seedLogger.success(`✅ ${sampleCharacters.length} personajes creados (Nexus Realms)`);
	} catch (error) {
		seedLogger.error('❌ Error creando personajes:', error);
		throw error;
	}
}
