import type { LibSQLDatabase } from 'drizzle-orm/libsql';
import { places } from '../schema';
import { seedLogger } from './index';

/**
 * Siembra lugares completos con jerarquía para demostración
 * Mundo: "Nexus Realms" - Fantasy & Cyberpunk
 */
export async function seedPlaces(db: LibSQLDatabase<Record<string, never>>) {
	seedLogger.info('📍 Creando lugares de ejemplo completos...');

	try {
		const samplePlaces = [
			// LUGARES RAÍZ
			{
				id: 'place-1',
				name: 'Reino de Lumina',
				description: 'Reino de luz y magia, hogar de los reinos fantasy tradicionales',
				emoji: '✨',
				color: '#f59e0b',
				category: 'reino',
				isPublic: true,
				isFavorite: true,
				totalImages: 0,
				totalVideos: 0,
				type: 'realm',
				location: 'Plano Material - Norte',
				climate: 'Variado',
				population: '5M+',
				government: 'Monarquía federal',
				economy: 'Magia y comercio',
				culture: 'Fantasy tradicional',
				history: 'Fundado tras la Gran Guerra de las Sombras',
				geography: 'Bosques, montañas, llanuras',
				landmarks: 'Palacio de Cristal, Torre de Zephyr',
				dangers: 'Media - criaturas mágicas',
				resources: 'Cristales mágicos, hierbas',
				notes: 'Reino principal fantasy',
				featuredImage: null,
				parentId: null,
			},
			{
				id: 'place-2',
				name: 'Neo-Tokyo Megacity',
				description: 'Megalópolis cyberpunk, hub tecnológico del mundo moderno',
				emoji: '🌃',
				color: '#06b6d4',
				category: 'megaciudad',
				isPublic: true,
				isFavorite: true,
				totalImages: 0,
				totalVideos: 0,
				type: 'urban',
				location: 'Plano Material - Este',
				climate: 'Controlado',
				population: '50M+',
				government: 'Corporatocracia',
				economy: 'Tech, IA, nanotecnología',
				culture: 'Cyberpunk, fusión cultural',
				history: 'Reconstruida tras el Colapso Digital',
				geography: 'Rascacielos, suburbios subterráneos',
				landmarks: 'Torre GenoTech, Red Cuántica Central',
				dangers: 'Alta - crimen corporativo',
				resources: 'Datos, energía cuántica',
				notes: 'Ciudad principal cyberpunk',
				featuredImage: null,
				parentId: null,
			},

			// HIJOS DE LUMINA
			{
				id: 'place-3',
				name: 'Bosque de Plata',
				description: 'Hogar ancestral de los elfos, lugar sagrado de Luna',
				emoji: '🌲',
				color: '#10b981',
				category: 'bosque',
				isPublic: true,
				isFavorite: false,
				totalImages: 0,
				totalVideos: 0,
				type: 'forest',
				location: 'Lumina - Noroeste',
				climate: 'Templado húmedo',
				population: '50K elfos',
				government: 'Consejo druídico',
				economy: 'Autosuficiente',
				culture: 'Élfica, comunión naturaleza',
				history: 'Hogar de Aria antes de la destrucción',
				geography: 'Bosque antiguo, ríos cristalinos',
				landmarks: 'Árbol Madre, Santuario de Luna',
				dangers: 'Baja - protegido',
				resources: 'Madera sagrada, hierbas mágicas',
				notes: 'Lugar de origen de Aria',
				featuredImage: null,
				parentId: 'place-1',
			},
			{
				id: 'place-4',
				name: 'Torre de Cristal',
				description: 'Academia de magia de Zephyr, biblioteca del conocimiento',
				emoji: '🗼',
				color: '#8b5cf6',
				category: 'academia',
				isPublic: false,
				isFavorite: true,
				totalImages: 0,
				totalVideos: 0,
				type: 'tower',
				location: 'Lumina - Centro',
				climate: 'Mágicamente estable',
				population: '500 magos',
				government: 'Archimago Zephyr',
				economy: 'Conocimiento',
				culture: 'Académica arcana',
				history: 'Fundada hace 800 años por Zephyr',
				geography: 'Torre flotante',
				landmarks: 'Biblioteca Infinita, Observatorio Astral',
				dangers: 'Alta - experimentos mágicos',
				resources: 'Libros antiguos, cristales',
				notes: 'Base de Zephyr',
				featuredImage: null,
				parentId: 'place-1',
			},
			{
				id: 'place-5',
				name: 'Fortaleza Sombría',
				description: 'Bastión oscuro de Lord Shadowbane, tierra maldita',
				emoji: '🏰',
				color: '#7c3aed',
				category: 'fortaleza',
				isPublic: false,
				isFavorite: false,
				totalImages: 0,
				totalVideos: 0,
				type: 'fortress',
				location: 'Lumina - Tierras Malditas',
				climate: 'Eterno crepúsculo',
				population: '10K cultistas',
				government: 'Tiranía de Shadowbane',
				economy: 'Saqueo, magia oscura',
				culture: 'Culto a las sombras',
				history: 'Conquistada por Shadowbane hace 10 años',
				geography: 'Montañas negras, tierras yermas',
				landmarks: 'Trono de Sombras, Portal del Vacío',
				dangers: 'Extrema - magia oscura',
				resources: 'Artefactos malditos',
				notes: 'Base del antagonista',
				featuredImage: null,
				parentId: 'place-1',
			},

			// HIJOS DE NEO-TOKYO
			{
				id: 'place-6',
				name: 'Distrito Corporativo',
				description: 'Torres de las megacorporaciones, corazón del poder',
				emoji: '🏢',
				color: '#ef4444',
				category: 'distrito',
				isPublic: true,
				isFavorite: false,
				totalImages: 0,
				totalVideos: 0,
				type: 'district',
				location: 'Neo-Tokyo - Alto Nivel',
				climate: 'Controlado premium',
				population: '1M ejecutivos',
				government: 'Consejos corporativos',
				economy: 'Finanzas, tech',
				culture: 'Elite corporativa',
				history: 'Centro del poder post-Colapso',
				geography: 'Rascacielos, skywalks',
				landmarks: 'Torre GenoTech, Bolsa Cuántica',
				dangers: 'Alta - espionaje corporativo',
				resources: 'Capital, tecnología',
				notes: 'Base de Dr. Helix',
				featuredImage: null,
				parentId: 'place-2',
			},
			{
				id: 'place-7',
				name: 'Suburbios Bajos',
				description: 'Niveles inferiores, hogar de hackers y rebeldes',
				emoji: '🌆',
				color: '#64748b',
				category: 'suburbios',
				isPublic: true,
				isFavorite: false,
				totalImages: 0,
				totalVideos: 0,
				type: 'district',
				location: 'Neo-Tokyo - Nivel 0-5',
				climate: 'Húmedo, smog',
				population: '30M ciudadanos',
				government: 'Gangs locales',
				economy: 'Mercado negro, servicios',
				culture: 'Contracultural, diversa',
				history: 'Donde vive la gente real',
				geography: 'Callejones, mercados, clubes',
				landmarks: 'Club Neon, Mercado de Chips',
				dangers: 'Media - crimen organizado',
				resources: 'Tech reciclada, información',
				notes: 'Hogar de Marcus y Nova',
				featuredImage: null,
				parentId: 'place-2',
			},
			{
				id: 'place-8',
				name: 'La Red Cuántica',
				description: 'Espacio digital donde vive Nova, realidad virtual',
				emoji: '🌐',
				color: '#ec4899',
				category: 'virtual',
				isPublic: false,
				isFavorite: true,
				totalImages: 0,
				totalVideos: 0,
				type: 'digital',
				location: 'Ciberespacio Global',
				climate: 'Digital',
				population: 'Infinitas IAs',
				government: 'Consenso de IA',
				economy: 'Datos e información',
				culture: 'Post-humana digital',
				history: 'Emergió durante el Gran Despertar',
				geography: 'Nodos, servidores, espacios virtuales',
				landmarks: 'Núcleo Central, Jardines de Datos',
				dangers: 'Variable - virus, hackers',
				resources: 'Conocimiento total',
				notes: 'Hogar de Nova Chrome',
				featuredImage: null,
				parentId: 'place-2',
			},
		];

		await db.insert(places).values(samplePlaces);

		seedLogger.success(`✅ ${samplePlaces.length} lugares creados (con jerarquía)`);
	} catch (error) {
		seedLogger.error('❌ Error creando lugares:', error);
		throw error;
	}
}
