import type { LibSQLDatabase } from 'drizzle-orm/libsql';
import { worldItems } from '../schema';
import { seedLogger } from './index';

/**
 * Siembra objetos del mundo minimalistas para verificación del sistema
 */
export async function seedWorldItems(db: LibSQLDatabase<Record<string, never>>) {
	seedLogger.info('🎯 Creando world items de prueba...');

	try {
		const sampleWorldItems = [
			{
				id: 'worlditem-1',
				name: 'Espadas Gemelas "Tempestad"',
				description: 'Espadas élfico-tecnológicas de Aria que canalizan vientos arcanos',
				emoji: '⚔️',
				color: '#06b6d4',
				category: 'arma',
				isPublic: true,
				isFavorite: true,
				totalImages: 0,
				totalVideos: 0,
				type: 'arma dual',
				rarity: 'épica',
				value: '50000',
				weight: '1.5kg cada una',
				materials: 'acero lunar, cristales de tormenta',
				origin: 'Forjadas en los talleres de Lumina',
				properties: 'Control de vientos, corte elemental',
				uses: 'Combate cuerpo a cuerpo, canalización mágica',
				history: 'Heredadas de la línea élfica de Aria',
				notes: 'Arma insignia de Aria Stormwind',
				featuredImage: null,
				parentId: null,
			},
			{
				id: 'worlditem-2',
				name: 'Deck Neural de Marcus',
				description: 'Interfaz de hacking neural de última generación',
				emoji: '💾',
				color: '#3b82f6',
				category: 'tech',
				isPublic: true,
				isFavorite: true,
				totalImages: 0,
				totalVideos: 0,
				type: 'dispositivo',
				rarity: 'rara',
				value: '25000',
				weight: '0.3kg',
				materials: 'chips cuánticos, fibra neural',
				origin: 'Mercado negro de Neo-Tokyo',
				properties: 'Hackeo avanzado, bypass de seguridad',
				uses: 'Infiltración digital, control de sistemas',
				history: 'Modificado por Marcus durante años',
				notes: 'Herramienta principal de Marcus Cross',
				featuredImage: null,
				parentId: null,
			},
			{
				id: 'worlditem-3',
				name: 'Bastón del Vacío',
				description: 'Bastón ancestral de Zephyr que controla energías dimensionales',
				emoji: '🪄',
				color: '#8b5cf6',
				category: 'arma',
				isPublic: true,
				isFavorite: true,
				totalImages: 0,
				totalVideos: 0,
				type: 'bastón mágico',
				rarity: 'legendaria',
				value: '100000',
				weight: '1kg',
				materials: 'madera del árbol del tiempo, gema del vacío',
				origin: 'Torre de los Magos Antiguos',
				properties: 'Portal dimensional, manipulación temporal',
				uses: 'Magia avanzada, teletransporte',
				history: 'Pasado de maestro a aprendiz por siglos',
				notes: 'Arma y foco mágico de Zephyr',
				featuredImage: null,
				parentId: null,
			},
			{
				id: 'worlditem-4',
				name: 'Espada Maldita "Nightfall"',
				description: 'Espada oscura que absorbe la luz y la vida',
				emoji: '🗡️',
				color: '#1f2937',
				category: 'arma',
				isPublic: true,
				isFavorite: false,
				totalImages: 0,
				totalVideos: 0,
				type: 'arma maldita',
				rarity: 'legendaria',
				value: '???',
				weight: '3kg',
				materials: 'acero sombrío, esencia de vacío',
				origin: 'Forjada en ritual prohibido',
				properties: 'Absorción de vida, corrupción',
				uses: 'Combate, ritual oscuro',
				history: 'Arma de Shadowbane, ha matado a cientos',
				notes: 'Extremadamente peligrosa',
				featuredImage: null,
				parentId: null,
			},
			{
				id: 'worlditem-5',
				name: 'Nano-inyector del Dr. Helix',
				description: 'Dispositivo médico que administra nanobots programables',
				emoji: '💉',
				color: '#10b981',
				category: 'tech',
				isPublic: true,
				isFavorite: false,
				totalImages: 0,
				totalVideos: 0,
				type: 'dispositivo médico',
				rarity: 'rara',
				value: '15000',
				weight: '0.2kg',
				materials: 'titanio médico, nanobots',
				origin: 'Laboratorios de Neo-Tokyo',
				properties: 'Curación rápida, mejora temporal',
				uses: 'Medicina, mejora biológica',
				history: 'Prototipo experimental del Dr. Helix',
				notes: 'Puede ser usado para bien o mal',
				featuredImage: null,
				parentId: null,
			},
			{
				id: 'worlditem-6',
				name: 'Amuleto del Equilibrio',
				description: 'Artefacto místico que detecta desequilibrios en la realidad',
				emoji: '🔱',
				color: '#f59e0b',
				category: 'artefacto',
				isPublic: true,
				isFavorite: true,
				totalImages: 0,
				totalVideos: 0,
				type: 'amuleto',
				rarity: 'única',
				value: 'invaluable',
				weight: '0.1kg',
				materials: 'cristal de equilibrio, oro celestial',
				origin: 'Guardado en Lumina',
				properties: 'Detección de anomalías, protección',
				uses: 'Monitoreo del equilibrio cósmico',
				history: 'Creado durante la era de los Antiguos',
				notes: 'Clave para la profecía del Equilibrio',
				featuredImage: null,
				parentId: null,
			},
		];

		await db.insert(worldItems).values(sampleWorldItems);

		seedLogger.success(`✅ ${sampleWorldItems.length} world items creados`);
	} catch (error) {
		seedLogger.error('❌ Error creando world items:', error);
		throw error;
	}
}
