import type { LayerImplementation } from '../types';
import { TextureLayer } from './components/texture-layer';
import { TextureSettings } from './components/texture-settings';
import { DEFAULT_CONFIG, TEXTURE_PRESETS, type TextureConfig } from './texture-config-types';

export const textureImplementation: LayerImplementation<TextureConfig> = {
	type: 'texture',
	name: 'Textura',
	description: 'Añade texturas personalizables a la tarjeta',
	icon: '��️',
	defaultConfig: DEFAULT_CONFIG,
	render: TextureLayer,
	settings: TextureSettings,
	presets: [
		{
			name: 'Papel Vintage',
			description: 'Textura de papel envejecido con efecto sutil',
			config: {
				enabled: true,
				visibleOnHover: false,
				layerIndex: 2,
				textureUrl: TEXTURE_PRESETS.PAPER.url,
				opacity: 0.15,
				scale: 1,
				rotation: 0,
				blendMode: 'multiply',
				offsetX: 0,
				offsetY: 0,
				tileMode: 'repeat',
				filters: {
					brightness: 90,
					contrast: 110,
					saturation: 80,
					blur: 0,
				},
			},
		},
		{
			name: 'Metal Pulido',
			description: 'Acabado metálico brillante y moderno',
			config: {
				enabled: true,
				visibleOnHover: false,
				layerIndex: 2,
				textureUrl: TEXTURE_PRESETS.METAL.url,
				opacity: 0.2,
				scale: 1.5,
				rotation: 45,
				blendMode: 'overlay',
				offsetX: 0,
				offsetY: 0,
				tileMode: 'repeat',
				filters: {
					brightness: 120,
					contrast: 130,
					saturation: 90,
					blur: 0.5,
				},
			},
		},
		{
			name: 'Madera Natural',
			description: 'Textura de madera con vetas naturales',
			config: {
				enabled: true,
				visibleOnHover: false,
				layerIndex: 2,
				textureUrl: TEXTURE_PRESETS.WOOD.url,
				opacity: 0.25,
				scale: 1.2,
				rotation: 0,
				blendMode: 'soft-light',
				offsetX: 0,
				offsetY: 0,
				tileMode: 'repeat',
				filters: {
					brightness: 105,
					contrast: 115,
					saturation: 95,
					blur: 0,
				},
			},
		},
		{
			name: 'Concreto Industrial',
			description: 'Textura de concreto con efecto industrial',
			config: {
				enabled: true,
				visibleOnHover: false,
				layerIndex: 2,
				textureUrl: TEXTURE_PRESETS.CONCRETE.url,
				opacity: 0.18,
				scale: 2,
				rotation: 0,
				blendMode: 'overlay',
				offsetX: 0,
				offsetY: 0,
				tileMode: 'repeat',
				filters: {
					brightness: 95,
					contrast: 120,
					saturation: 85,
					blur: 0.3,
				},
			},
		},
		{
			name: 'Tela Suave',
			description: 'Textura de tela con efecto delicado',
			config: {
				enabled: true,
				visibleOnHover: false,
				layerIndex: 2,
				textureUrl: TEXTURE_PRESETS.FABRIC.url,
				opacity: 0.12,
				scale: 1.8,
				rotation: 30,
				blendMode: 'soft-light',
				offsetX: 0,
				offsetY: 0,
				tileMode: 'repeat',
				filters: {
					brightness: 102,
					contrast: 105,
					saturation: 98,
					blur: 0.2,
				},
			},
		},
	],
};