import { BordersIcon } from 'lucide-react';
import { AnimatedBorderLayer } from './components/animated-border-layer';
import { AnimatedBorderSettings } from './components/animated-border-settings';

export const animatedBorderImplementation = {
	type: 'animated-border',
	name: 'Borde Animado',
	description: 'Añade un borde animado a la tarjeta con efectos personalizables',
	icon: BordersIcon,
	defaultConfig: {
		enabled: true,
		visibleOnHover: false,
		layerIndex: 1,
		opacity: 1,
		color: '#ffffff',
		width: 2,
		speed: 0.001,
		segments: 4,
		blendMode: 'normal',
	},
	component: AnimatedBorderLayer,
	settings: AnimatedBorderSettings,
	presets: [
		{
			name: 'Borde Suave',
			description: 'Un borde suave y elegante que fluye alrededor de la tarjeta',
			config: {
				enabled: true,
				visibleOnHover: false,
				layerIndex: 1,
				opacity: 0.8,
				color: '#ffffff',
				width: 2,
				speed: 0.0005,
				segments: 4,
				blendMode: 'soft-light',
			},
		},
		{
			name: 'Borde Energético',
			description: 'Un borde rápido y dinámico con colores vibrantes',
			config: {
				enabled: true,
				visibleOnHover: false,
				layerIndex: 1,
				opacity: 1,
				color: '#00ff00',
				width: 3,
				speed: 0.002,
				segments: 6,
				blendMode: 'screen',
			},
		},
		{
			name: 'Borde Místico',
			description: 'Un borde místico con efecto de brillo y movimiento suave',
			config: {
				enabled: true,
				visibleOnHover: true,
				layerIndex: 1,
				opacity: 0.9,
				color: '#9f7aea',
				width: 2.5,
				speed: 0.001,
				segments: 8,
				blendMode: 'color-dodge',
			},
		},
		{
			name: 'Borde Futurista',
			description: 'Un borde tecnológico con aspecto digital y movimiento rápido',
			config: {
				enabled: true,
				visibleOnHover: false,
				layerIndex: 1,
				opacity: 1,
				color: '#00ffff',
				width: 1.5,
				speed: 0.003,
				segments: 12,
				blendMode: 'screen',
			},
		},
	],
};