import type { LayerImplementation } from '../types';
import type { GrainConfig } from './actions/grain-config.action';
import { GrainLayer } from './components/grain-layer';
import { GrainSettings } from './components/grain-settings';

/**
 * 🌾 Implementación de la capa de grano
 * @module GrainLayer
 */
export const grainImplementation: LayerImplementation<GrainConfig> = {
	type: 'grain',
	name: 'Grano',
	description: 'Añade un efecto de grano para simular texturas de película o papel',
	icon: '🌾',
	defaultConfig: {
		enabled: true,
		intensity: 0.15,
		size: 1,
		animated: false,
		speed: 5,
		colorMode: 'monochrome',
		opacity: 0.5,
		blend: 'overlay',
		seed: 42,
		pattern: 'perlin',
		fractalNoise: false,
		roughness: 0.5,
		distribution: 'gaussian',
		layerIndex: 6,
	},
	render: GrainLayer,
	settings: GrainSettings,
	presets: [
		{
			name: 'Película Clásica',
			description: 'Grano suave monocromático para un look cinematográfico',
			config: {
				enabled: true,
				intensity: 0.15,
				size: 1,
				animated: false,
				speed: 0,
				colorMode: 'monochrome',
				opacity: 0.4,
				blend: 'overlay',
				seed: 42,
				pattern: 'perlin',
				fractalNoise: false,
				roughness: 0.5,
				distribution: 'gaussian',
				layerIndex: 6,
			},
		},
		{
			name: 'Ruido Digital',
			description: 'Grano digital animado para efectos modernos',
			config: {
				enabled: true,
				intensity: 0.2,
				size: 0.8,
				animated: true,
				speed: 8,
				colorMode: 'color',
				opacity: 0.3,
				blend: 'screen',
				seed: 123,
				pattern: 'simplex',
				fractalNoise: true,
				roughness: 0.7,
				distribution: 'uniform',
				layerIndex: 6,
			},
		},
		{
			name: 'Papel Texturizado',
			description: 'Grano sutil que simula textura de papel',
			config: {
				enabled: true,
				intensity: 0.1,
				size: 1.5,
				animated: false,
				speed: 0,
				colorMode: 'monochrome',
				opacity: 0.25,
				blend: 'multiply',
				seed: 789,
				pattern: 'worley',
				fractalNoise: false,
				roughness: 0.3,
				distribution: 'gaussian',
				layerIndex: 6,
			},
		},
		{
			name: 'Ruido Intenso',
			description: 'Grano fuerte para efectos dramáticos',
			config: {
				enabled: true,
				intensity: 0.35,
				size: 0.6,
				animated: true,
				speed: 3,
				colorMode: 'monochrome',
				opacity: 0.6,
				blend: 'overlay',
				seed: 456,
				pattern: 'perlin',
				fractalNoise: true,
				roughness: 0.8,
				distribution: 'uniform',
				layerIndex: 6,
			},
		},
		{
			name: 'Grano Sutil',
			description: 'Grano muy suave para efectos delicados',
			config: {
				enabled: true,
				intensity: 0.08,
				size: 1.2,
				animated: false,
				speed: 0,
				colorMode: 'monochrome',
				opacity: 0.2,
				blend: 'soft-light',
				seed: 999,
				pattern: 'simplex',
				fractalNoise: false,
				roughness: 0.4,
				distribution: 'gaussian',
				layerIndex: 6,
			},
		},
	],
};