import { BorderAllIcon } from 'lucide-react';
import { BorderLayer } from './components/border-layer';
import { BorderSettings } from './components/border-settings';

export const borderImplementation = {
	type: 'border',
	name: 'Borde',
	description: 'Añade un borde personalizable a la tarjeta con efectos y estilos',
	icon: BorderAllIcon,
	defaultConfig: {
		enabled: true,
		visibleOnHover: false,
		layerIndex: 2,
		opacity: 1,
		color: '#ffffff',
		width: 1,
		style: 'solid',
		radius: 0,
		blendMode: 'normal',
		glow: false,
		glowColor: '#ffffff',
		glowRadius: 10,
		gradient: false,
		gradientAngle: 45,
		gradientColors: ['#ffffff', '#000000'],
	},
	component: BorderLayer,
	settings: BorderSettings,
	presets: [
		{
			name: 'Borde Clásico',
			description: 'Un borde sólido y elegante',
			config: {
				enabled: true,
				visibleOnHover: false,
				layerIndex: 2,
				opacity: 1,
				color: '#ffffff',
				width: 2,
				style: 'solid',
				radius: 4,
				blendMode: 'normal',
			},
		},
		{
			name: 'Borde Neón',
			description: 'Un borde brillante con efecto de neón',
			config: {
				enabled: true,
				visibleOnHover: false,
				layerIndex: 2,
				opacity: 1,
				color: '#00ff00',
				width: 2,
				style: 'solid',
				radius: 8,
				blendMode: 'screen',
				glow: true,
				glowColor: '#00ff00',
				glowRadius: 15,
			},
		},
		{
			name: 'Borde Gradiente',
			description: 'Un borde con gradiente de colores',
			config: {
				enabled: true,
				visibleOnHover: false,
				layerIndex: 2,
				opacity: 1,
				width: 3,
				style: 'solid',
				radius: 0,
				blendMode: 'normal',
				gradient: true,
				gradientAngle: 45,
				gradientColors: ['#ff0000', '#00ff00', '#0000ff'],
			},
		},
		{
			name: 'Borde Punteado',
			description: 'Un borde punteado con efecto sutil',
			config: {
				enabled: true,
				visibleOnHover: true,
				layerIndex: 2,
				opacity: 0.8,
				color: '#ffffff',
				width: 2,
				style: 'dotted',
				radius: 12,
				blendMode: 'overlay',
			},
		},
		{
			name: 'Borde Ciberpunk',
			description: 'Un borde futurista con gradiente y brillo',
			config: {
				enabled: true,
				visibleOnHover: false,
				layerIndex: 2,
				opacity: 1,
				width: 3,
				style: 'solid',
				radius: 0,
				blendMode: 'screen',
				gradient: true,
				gradientAngle: 90,
				gradientColors: ['#ff00ff', '#00ffff'],
				glow: true,
				glowColor: '#ff00ff',
				glowRadius: 20,
			},
		},
	],
};