// Exportar cliente de base de datos y repositorio
export { db, drizzleDb } from './db';
export { DrizzleRepository } from './repository';

// Exportar esquema completo para uso con Drizzle ORM
export * from './schema';

// Exportar tipos inferidos
import type {
    Album,
    AlbumInsert,
    Character,
    CharacterInsert,
    Collection,
    CollectionInsert,
    Concept,
    ConceptInsert,
    Folder,
    FolderInsert,
    Group,
    GroupInsert,
    Image,
    ImageInsert,
    ImageStats,
    ImageStatsInsert,
    Note,
    NoteInsert,
    Place,
    PlaceInsert,
    Profile,
    ProfileInsert,
    Prompt,
    PromptInsert,
    Property,
    PropertyInsert,
    Queue,
    QueueInsert,
    Settings,
    SettingsInsert,
    Tag,
    TagInsert,
    UploadedImage,
    UploadedImageInsert,
    Video,
    VideoInsert,
    Wildcard,
    WildcardInsert,
    WorldItem,
    WorldItemInsert,
} from './schema/types';

// Re-exportar tipos para uso en la aplicación
export type {
    Album,
    AlbumInsert,
    Character,
    CharacterInsert,
    Collection,
    CollectionInsert,
    Concept,
    ConceptInsert,
    Folder,
    FolderInsert,
    Group,
    GroupInsert,
    Image,
    ImageInsert,
    ImageStats,
    ImageStatsInsert,
    Note,
    NoteInsert,
    Place,
    PlaceInsert,
    Profile,
    ProfileInsert,
    Prompt,
    PromptInsert,
    Property,
    PropertyInsert,
    Queue,
    QueueInsert,
    Settings,
    SettingsInsert,
    Tag,
    TagInsert,
    UploadedImage,
    UploadedImageInsert,
    Video,
    VideoInsert,
    Wildcard,
    WildcardInsert,
    WorldItem,
    WorldItemInsert
};

