-- Data-only compatibility migration. The historical baseline declared INTEGER columns with
-- CURRENT_TIMESTAMP defaults, which SQLite persisted as TEXT. Normalize every canonical
-- timestamp_ms column and then fail closed if any non-null value is still not an integer.

UPDATE `Activity` SET `createdAt` = CASE WHEN typeof(`createdAt`) = 'text' AND strftime('%s', `createdAt`) IS NOT NULL THEN CAST(strftime('%s', `createdAt`) AS INTEGER) * 1000 WHEN typeof(`createdAt`) IN ('integer', 'real') AND abs(`createdAt`) < 100000000000 THEN CAST(`createdAt` * 1000 AS INTEGER) WHEN typeof(`createdAt`) = 'real' THEN CAST(`createdAt` AS INTEGER) ELSE `createdAt` END;--> statement-breakpoint
UPDATE `Album` SET
	`lastImageAddedAt` = CASE WHEN typeof(`lastImageAddedAt`) = 'text' AND strftime('%s', `lastImageAddedAt`) IS NOT NULL THEN CAST(strftime('%s', `lastImageAddedAt`) AS INTEGER) * 1000 WHEN typeof(`lastImageAddedAt`) IN ('integer', 'real') AND abs(`lastImageAddedAt`) < 100000000000 THEN CAST(`lastImageAddedAt` * 1000 AS INTEGER) WHEN typeof(`lastImageAddedAt`) = 'real' THEN CAST(`lastImageAddedAt` AS INTEGER) ELSE `lastImageAddedAt` END,
	`lastVideoAddedAt` = CASE WHEN typeof(`lastVideoAddedAt`) = 'text' AND strftime('%s', `lastVideoAddedAt`) IS NOT NULL THEN CAST(strftime('%s', `lastVideoAddedAt`) AS INTEGER) * 1000 WHEN typeof(`lastVideoAddedAt`) IN ('integer', 'real') AND abs(`lastVideoAddedAt`) < 100000000000 THEN CAST(`lastVideoAddedAt` * 1000 AS INTEGER) WHEN typeof(`lastVideoAddedAt`) = 'real' THEN CAST(`lastVideoAddedAt` AS INTEGER) ELSE `lastVideoAddedAt` END,
	`createdAt` = CASE WHEN typeof(`createdAt`) = 'text' AND strftime('%s', `createdAt`) IS NOT NULL THEN CAST(strftime('%s', `createdAt`) AS INTEGER) * 1000 WHEN typeof(`createdAt`) IN ('integer', 'real') AND abs(`createdAt`) < 100000000000 THEN CAST(`createdAt` * 1000 AS INTEGER) WHEN typeof(`createdAt`) = 'real' THEN CAST(`createdAt` AS INTEGER) ELSE `createdAt` END,
	`updatedAt` = CASE WHEN typeof(`updatedAt`) = 'text' AND strftime('%s', `updatedAt`) IS NOT NULL THEN CAST(strftime('%s', `updatedAt`) AS INTEGER) * 1000 WHEN typeof(`updatedAt`) IN ('integer', 'real') AND abs(`updatedAt`) < 100000000000 THEN CAST(`updatedAt` * 1000 AS INTEGER) WHEN typeof(`updatedAt`) = 'real' THEN CAST(`updatedAt` AS INTEGER) ELSE `updatedAt` END;--> statement-breakpoint
UPDATE `Audio` SET `createdAt` = CASE WHEN typeof(`createdAt`) = 'text' AND strftime('%s', `createdAt`) IS NOT NULL THEN CAST(strftime('%s', `createdAt`) AS INTEGER) * 1000 WHEN typeof(`createdAt`) IN ('integer', 'real') AND abs(`createdAt`) < 100000000000 THEN CAST(`createdAt` * 1000 AS INTEGER) WHEN typeof(`createdAt`) = 'real' THEN CAST(`createdAt` AS INTEGER) ELSE `createdAt` END, `updatedAt` = CASE WHEN typeof(`updatedAt`) = 'text' AND strftime('%s', `updatedAt`) IS NOT NULL THEN CAST(strftime('%s', `updatedAt`) AS INTEGER) * 1000 WHEN typeof(`updatedAt`) IN ('integer', 'real') AND abs(`updatedAt`) < 100000000000 THEN CAST(`updatedAt` * 1000 AS INTEGER) WHEN typeof(`updatedAt`) = 'real' THEN CAST(`updatedAt` AS INTEGER) ELSE `updatedAt` END;--> statement-breakpoint
UPDATE `Character` SET `createdAt` = CASE WHEN typeof(`createdAt`) = 'text' AND strftime('%s', `createdAt`) IS NOT NULL THEN CAST(strftime('%s', `createdAt`) AS INTEGER) * 1000 WHEN typeof(`createdAt`) IN ('integer', 'real') AND abs(`createdAt`) < 100000000000 THEN CAST(`createdAt` * 1000 AS INTEGER) WHEN typeof(`createdAt`) = 'real' THEN CAST(`createdAt` AS INTEGER) ELSE `createdAt` END, `updatedAt` = CASE WHEN typeof(`updatedAt`) = 'text' AND strftime('%s', `updatedAt`) IS NOT NULL THEN CAST(strftime('%s', `updatedAt`) AS INTEGER) * 1000 WHEN typeof(`updatedAt`) IN ('integer', 'real') AND abs(`updatedAt`) < 100000000000 THEN CAST(`updatedAt` * 1000 AS INTEGER) WHEN typeof(`updatedAt`) = 'real' THEN CAST(`updatedAt` AS INTEGER) ELSE `updatedAt` END;--> statement-breakpoint
UPDATE `Collection` SET
	`lastImageAddedAt` = CASE WHEN typeof(`lastImageAddedAt`) = 'text' AND strftime('%s', `lastImageAddedAt`) IS NOT NULL THEN CAST(strftime('%s', `lastImageAddedAt`) AS INTEGER) * 1000 WHEN typeof(`lastImageAddedAt`) IN ('integer', 'real') AND abs(`lastImageAddedAt`) < 100000000000 THEN CAST(`lastImageAddedAt` * 1000 AS INTEGER) WHEN typeof(`lastImageAddedAt`) = 'real' THEN CAST(`lastImageAddedAt` AS INTEGER) ELSE `lastImageAddedAt` END,
	`lastVideoAddedAt` = CASE WHEN typeof(`lastVideoAddedAt`) = 'text' AND strftime('%s', `lastVideoAddedAt`) IS NOT NULL THEN CAST(strftime('%s', `lastVideoAddedAt`) AS INTEGER) * 1000 WHEN typeof(`lastVideoAddedAt`) IN ('integer', 'real') AND abs(`lastVideoAddedAt`) < 100000000000 THEN CAST(`lastVideoAddedAt` * 1000 AS INTEGER) WHEN typeof(`lastVideoAddedAt`) = 'real' THEN CAST(`lastVideoAddedAt` AS INTEGER) ELSE `lastVideoAddedAt` END,
	`createdAt` = CASE WHEN typeof(`createdAt`) = 'text' AND strftime('%s', `createdAt`) IS NOT NULL THEN CAST(strftime('%s', `createdAt`) AS INTEGER) * 1000 WHEN typeof(`createdAt`) IN ('integer', 'real') AND abs(`createdAt`) < 100000000000 THEN CAST(`createdAt` * 1000 AS INTEGER) WHEN typeof(`createdAt`) = 'real' THEN CAST(`createdAt` AS INTEGER) ELSE `createdAt` END,
	`updatedAt` = CASE WHEN typeof(`updatedAt`) = 'text' AND strftime('%s', `updatedAt`) IS NOT NULL THEN CAST(strftime('%s', `updatedAt`) AS INTEGER) * 1000 WHEN typeof(`updatedAt`) IN ('integer', 'real') AND abs(`updatedAt`) < 100000000000 THEN CAST(`updatedAt` * 1000 AS INTEGER) WHEN typeof(`updatedAt`) = 'real' THEN CAST(`updatedAt` AS INTEGER) ELSE `updatedAt` END;--> statement-breakpoint
UPDATE `Concept` SET `createdAt` = CASE WHEN typeof(`createdAt`) = 'text' AND strftime('%s', `createdAt`) IS NOT NULL THEN CAST(strftime('%s', `createdAt`) AS INTEGER) * 1000 WHEN typeof(`createdAt`) IN ('integer', 'real') AND abs(`createdAt`) < 100000000000 THEN CAST(`createdAt` * 1000 AS INTEGER) WHEN typeof(`createdAt`) = 'real' THEN CAST(`createdAt` AS INTEGER) ELSE `createdAt` END, `updatedAt` = CASE WHEN typeof(`updatedAt`) = 'text' AND strftime('%s', `updatedAt`) IS NOT NULL THEN CAST(strftime('%s', `updatedAt`) AS INTEGER) * 1000 WHEN typeof(`updatedAt`) IN ('integer', 'real') AND abs(`updatedAt`) < 100000000000 THEN CAST(`updatedAt` * 1000 AS INTEGER) WHEN typeof(`updatedAt`) = 'real' THEN CAST(`updatedAt` AS INTEGER) ELSE `updatedAt` END;--> statement-breakpoint
UPDATE `Document` SET
	`thumbnailErrorAt` = CASE WHEN typeof(`thumbnailErrorAt`) = 'text' AND strftime('%s', `thumbnailErrorAt`) IS NOT NULL THEN CAST(strftime('%s', `thumbnailErrorAt`) AS INTEGER) * 1000 WHEN typeof(`thumbnailErrorAt`) IN ('integer', 'real') AND abs(`thumbnailErrorAt`) < 100000000000 THEN CAST(`thumbnailErrorAt` * 1000 AS INTEGER) WHEN typeof(`thumbnailErrorAt`) = 'real' THEN CAST(`thumbnailErrorAt` AS INTEGER) ELSE `thumbnailErrorAt` END,
	`creationDate` = CASE WHEN typeof(`creationDate`) = 'text' AND strftime('%s', `creationDate`) IS NOT NULL THEN CAST(strftime('%s', `creationDate`) AS INTEGER) * 1000 WHEN typeof(`creationDate`) IN ('integer', 'real') AND abs(`creationDate`) < 100000000000 THEN CAST(`creationDate` * 1000 AS INTEGER) WHEN typeof(`creationDate`) = 'real' THEN CAST(`creationDate` AS INTEGER) ELSE `creationDate` END,
	`modificationDate` = CASE WHEN typeof(`modificationDate`) = 'text' AND strftime('%s', `modificationDate`) IS NOT NULL THEN CAST(strftime('%s', `modificationDate`) AS INTEGER) * 1000 WHEN typeof(`modificationDate`) IN ('integer', 'real') AND abs(`modificationDate`) < 100000000000 THEN CAST(`modificationDate` * 1000 AS INTEGER) WHEN typeof(`modificationDate`) = 'real' THEN CAST(`modificationDate` AS INTEGER) ELSE `modificationDate` END,
	`createdAt` = CASE WHEN typeof(`createdAt`) = 'text' AND strftime('%s', `createdAt`) IS NOT NULL THEN CAST(strftime('%s', `createdAt`) AS INTEGER) * 1000 WHEN typeof(`createdAt`) IN ('integer', 'real') AND abs(`createdAt`) < 100000000000 THEN CAST(`createdAt` * 1000 AS INTEGER) WHEN typeof(`createdAt`) = 'real' THEN CAST(`createdAt` AS INTEGER) ELSE `createdAt` END,
	`updatedAt` = CASE WHEN typeof(`updatedAt`) = 'text' AND strftime('%s', `updatedAt`) IS NOT NULL THEN CAST(strftime('%s', `updatedAt`) AS INTEGER) * 1000 WHEN typeof(`updatedAt`) IN ('integer', 'real') AND abs(`updatedAt`) < 100000000000 THEN CAST(`updatedAt` * 1000 AS INTEGER) WHEN typeof(`updatedAt`) = 'real' THEN CAST(`updatedAt` AS INTEGER) ELSE `updatedAt` END;--> statement-breakpoint
UPDATE `EntityAggregates` SET `lastIndexed` = CASE WHEN typeof(`lastIndexed`) = 'text' AND strftime('%s', `lastIndexed`) IS NOT NULL THEN CAST(strftime('%s', `lastIndexed`) AS INTEGER) * 1000 WHEN typeof(`lastIndexed`) IN ('integer', 'real') AND abs(`lastIndexed`) < 100000000000 THEN CAST(`lastIndexed` * 1000 AS INTEGER) WHEN typeof(`lastIndexed`) = 'real' THEN CAST(`lastIndexed` AS INTEGER) ELSE `lastIndexed` END, `updatedAt` = CASE WHEN typeof(`updatedAt`) = 'text' AND strftime('%s', `updatedAt`) IS NOT NULL THEN CAST(strftime('%s', `updatedAt`) AS INTEGER) * 1000 WHEN typeof(`updatedAt`) IN ('integer', 'real') AND abs(`updatedAt`) < 100000000000 THEN CAST(`updatedAt` * 1000 AS INTEGER) WHEN typeof(`updatedAt`) = 'real' THEN CAST(`updatedAt` AS INTEGER) ELSE `updatedAt` END;--> statement-breakpoint
UPDATE `Favorite` SET `addedAt` = CASE WHEN typeof(`addedAt`) = 'text' AND strftime('%s', `addedAt`) IS NOT NULL THEN CAST(strftime('%s', `addedAt`) AS INTEGER) * 1000 WHEN typeof(`addedAt`) IN ('integer', 'real') AND abs(`addedAt`) < 100000000000 THEN CAST(`addedAt` * 1000 AS INTEGER) WHEN typeof(`addedAt`) = 'real' THEN CAST(`addedAt` AS INTEGER) ELSE `addedAt` END;--> statement-breakpoint
UPDATE `File` SET `lastAccessed` = CASE WHEN typeof(`lastAccessed`) = 'text' AND strftime('%s', `lastAccessed`) IS NOT NULL THEN CAST(strftime('%s', `lastAccessed`) AS INTEGER) * 1000 WHEN typeof(`lastAccessed`) IN ('integer', 'real') AND abs(`lastAccessed`) < 100000000000 THEN CAST(`lastAccessed` * 1000 AS INTEGER) WHEN typeof(`lastAccessed`) = 'real' THEN CAST(`lastAccessed` AS INTEGER) ELSE `lastAccessed` END, `createdAt` = CASE WHEN typeof(`createdAt`) = 'text' AND strftime('%s', `createdAt`) IS NOT NULL THEN CAST(strftime('%s', `createdAt`) AS INTEGER) * 1000 WHEN typeof(`createdAt`) IN ('integer', 'real') AND abs(`createdAt`) < 100000000000 THEN CAST(`createdAt` * 1000 AS INTEGER) WHEN typeof(`createdAt`) = 'real' THEN CAST(`createdAt` AS INTEGER) ELSE `createdAt` END, `updatedAt` = CASE WHEN typeof(`updatedAt`) = 'text' AND strftime('%s', `updatedAt`) IS NOT NULL THEN CAST(strftime('%s', `updatedAt`) AS INTEGER) * 1000 WHEN typeof(`updatedAt`) IN ('integer', 'real') AND abs(`updatedAt`) < 100000000000 THEN CAST(`updatedAt` * 1000 AS INTEGER) WHEN typeof(`updatedAt`) = 'real' THEN CAST(`updatedAt` AS INTEGER) ELSE `updatedAt` END;--> statement-breakpoint
UPDATE `File3D` SET `createdAt` = CASE WHEN typeof(`createdAt`) = 'text' AND strftime('%s', `createdAt`) IS NOT NULL THEN CAST(strftime('%s', `createdAt`) AS INTEGER) * 1000 WHEN typeof(`createdAt`) IN ('integer', 'real') AND abs(`createdAt`) < 100000000000 THEN CAST(`createdAt` * 1000 AS INTEGER) WHEN typeof(`createdAt`) = 'real' THEN CAST(`createdAt` AS INTEGER) ELSE `createdAt` END, `updatedAt` = CASE WHEN typeof(`updatedAt`) = 'text' AND strftime('%s', `updatedAt`) IS NOT NULL THEN CAST(strftime('%s', `updatedAt`) AS INTEGER) * 1000 WHEN typeof(`updatedAt`) IN ('integer', 'real') AND abs(`updatedAt`) < 100000000000 THEN CAST(`updatedAt` * 1000 AS INTEGER) WHEN typeof(`updatedAt`) = 'real' THEN CAST(`updatedAt` AS INTEGER) ELSE `updatedAt` END;--> statement-breakpoint
UPDATE `FileStats` SET `createdAt` = CASE WHEN typeof(`createdAt`) = 'text' AND strftime('%s', `createdAt`) IS NOT NULL THEN CAST(strftime('%s', `createdAt`) AS INTEGER) * 1000 WHEN typeof(`createdAt`) IN ('integer', 'real') AND abs(`createdAt`) < 100000000000 THEN CAST(`createdAt` * 1000 AS INTEGER) WHEN typeof(`createdAt`) = 'real' THEN CAST(`createdAt` AS INTEGER) ELSE `createdAt` END, `updatedAt` = CASE WHEN typeof(`updatedAt`) = 'text' AND strftime('%s', `updatedAt`) IS NOT NULL THEN CAST(strftime('%s', `updatedAt`) AS INTEGER) * 1000 WHEN typeof(`updatedAt`) IN ('integer', 'real') AND abs(`updatedAt`) < 100000000000 THEN CAST(`updatedAt` * 1000 AS INTEGER) WHEN typeof(`updatedAt`) = 'real' THEN CAST(`updatedAt` AS INTEGER) ELSE `updatedAt` END;--> statement-breakpoint
UPDATE `Folder` SET `lastIndexed` = CASE WHEN typeof(`lastIndexed`) = 'text' AND strftime('%s', `lastIndexed`) IS NOT NULL THEN CAST(strftime('%s', `lastIndexed`) AS INTEGER) * 1000 WHEN typeof(`lastIndexed`) IN ('integer', 'real') AND abs(`lastIndexed`) < 100000000000 THEN CAST(`lastIndexed` * 1000 AS INTEGER) WHEN typeof(`lastIndexed`) = 'real' THEN CAST(`lastIndexed` AS INTEGER) ELSE `lastIndexed` END, `createdAt` = CASE WHEN typeof(`createdAt`) = 'text' AND strftime('%s', `createdAt`) IS NOT NULL THEN CAST(strftime('%s', `createdAt`) AS INTEGER) * 1000 WHEN typeof(`createdAt`) IN ('integer', 'real') AND abs(`createdAt`) < 100000000000 THEN CAST(`createdAt` * 1000 AS INTEGER) WHEN typeof(`createdAt`) = 'real' THEN CAST(`createdAt` AS INTEGER) ELSE `createdAt` END, `updatedAt` = CASE WHEN typeof(`updatedAt`) = 'text' AND strftime('%s', `updatedAt`) IS NOT NULL THEN CAST(strftime('%s', `updatedAt`) AS INTEGER) * 1000 WHEN typeof(`updatedAt`) IN ('integer', 'real') AND abs(`updatedAt`) < 100000000000 THEN CAST(`updatedAt` * 1000 AS INTEGER) WHEN typeof(`updatedAt`) = 'real' THEN CAST(`updatedAt` AS INTEGER) ELSE `updatedAt` END;--> statement-breakpoint
UPDATE `Group` SET `createdAt` = CASE WHEN typeof(`createdAt`) = 'text' AND strftime('%s', `createdAt`) IS NOT NULL THEN CAST(strftime('%s', `createdAt`) AS INTEGER) * 1000 WHEN typeof(`createdAt`) IN ('integer', 'real') AND abs(`createdAt`) < 100000000000 THEN CAST(`createdAt` * 1000 AS INTEGER) WHEN typeof(`createdAt`) = 'real' THEN CAST(`createdAt` AS INTEGER) ELSE `createdAt` END, `updatedAt` = CASE WHEN typeof(`updatedAt`) = 'text' AND strftime('%s', `updatedAt`) IS NOT NULL THEN CAST(strftime('%s', `updatedAt`) AS INTEGER) * 1000 WHEN typeof(`updatedAt`) IN ('integer', 'real') AND abs(`updatedAt`) < 100000000000 THEN CAST(`updatedAt` * 1000 AS INTEGER) WHEN typeof(`updatedAt`) = 'real' THEN CAST(`updatedAt` AS INTEGER) ELSE `updatedAt` END;--> statement-breakpoint
UPDATE `Image` SET
	`thumbnailErrorAt` = CASE WHEN typeof(`thumbnailErrorAt`) = 'text' AND strftime('%s', `thumbnailErrorAt`) IS NOT NULL THEN CAST(strftime('%s', `thumbnailErrorAt`) AS INTEGER) * 1000 WHEN typeof(`thumbnailErrorAt`) IN ('integer', 'real') AND abs(`thumbnailErrorAt`) < 100000000000 THEN CAST(`thumbnailErrorAt` * 1000 AS INTEGER) WHEN typeof(`thumbnailErrorAt`) = 'real' THEN CAST(`thumbnailErrorAt` AS INTEGER) ELSE `thumbnailErrorAt` END,
	`thumbnailOptimizedAt` = CASE WHEN typeof(`thumbnailOptimizedAt`) = 'text' AND strftime('%s', `thumbnailOptimizedAt`) IS NOT NULL THEN CAST(strftime('%s', `thumbnailOptimizedAt`) AS INTEGER) * 1000 WHEN typeof(`thumbnailOptimizedAt`) IN ('integer', 'real') AND abs(`thumbnailOptimizedAt`) < 100000000000 THEN CAST(`thumbnailOptimizedAt` * 1000 AS INTEGER) WHEN typeof(`thumbnailOptimizedAt`) = 'real' THEN CAST(`thumbnailOptimizedAt` AS INTEGER) ELSE `thumbnailOptimizedAt` END,
	`createdAt` = CASE WHEN typeof(`createdAt`) = 'text' AND strftime('%s', `createdAt`) IS NOT NULL THEN CAST(strftime('%s', `createdAt`) AS INTEGER) * 1000 WHEN typeof(`createdAt`) IN ('integer', 'real') AND abs(`createdAt`) < 100000000000 THEN CAST(`createdAt` * 1000 AS INTEGER) WHEN typeof(`createdAt`) = 'real' THEN CAST(`createdAt` AS INTEGER) ELSE `createdAt` END,
	`updatedAt` = CASE WHEN typeof(`updatedAt`) = 'text' AND strftime('%s', `updatedAt`) IS NOT NULL THEN CAST(strftime('%s', `updatedAt`) AS INTEGER) * 1000 WHEN typeof(`updatedAt`) IN ('integer', 'real') AND abs(`updatedAt`) < 100000000000 THEN CAST(`updatedAt` * 1000 AS INTEGER) WHEN typeof(`updatedAt`) = 'real' THEN CAST(`updatedAt` AS INTEGER) ELSE `updatedAt` END,
	`addedAt` = CASE WHEN typeof(`addedAt`) = 'text' AND strftime('%s', `addedAt`) IS NOT NULL THEN CAST(strftime('%s', `addedAt`) AS INTEGER) * 1000 WHEN typeof(`addedAt`) IN ('integer', 'real') AND abs(`addedAt`) < 100000000000 THEN CAST(`addedAt` * 1000 AS INTEGER) WHEN typeof(`addedAt`) = 'real' THEN CAST(`addedAt` AS INTEGER) ELSE `addedAt` END;--> statement-breakpoint
UPDATE `JsonFile` SET `createdAt` = CASE WHEN typeof(`createdAt`) = 'text' AND strftime('%s', `createdAt`) IS NOT NULL THEN CAST(strftime('%s', `createdAt`) AS INTEGER) * 1000 WHEN typeof(`createdAt`) IN ('integer', 'real') AND abs(`createdAt`) < 100000000000 THEN CAST(`createdAt` * 1000 AS INTEGER) WHEN typeof(`createdAt`) = 'real' THEN CAST(`createdAt` AS INTEGER) ELSE `createdAt` END, `updatedAt` = CASE WHEN typeof(`updatedAt`) = 'text' AND strftime('%s', `updatedAt`) IS NOT NULL THEN CAST(strftime('%s', `updatedAt`) AS INTEGER) * 1000 WHEN typeof(`updatedAt`) IN ('integer', 'real') AND abs(`updatedAt`) < 100000000000 THEN CAST(`updatedAt` * 1000 AS INTEGER) WHEN typeof(`updatedAt`) = 'real' THEN CAST(`updatedAt` AS INTEGER) ELSE `updatedAt` END;--> statement-breakpoint
UPDATE `Metadata` SET `createdAt` = CASE WHEN typeof(`createdAt`) = 'text' AND strftime('%s', `createdAt`) IS NOT NULL THEN CAST(strftime('%s', `createdAt`) AS INTEGER) * 1000 WHEN typeof(`createdAt`) IN ('integer', 'real') AND abs(`createdAt`) < 100000000000 THEN CAST(`createdAt` * 1000 AS INTEGER) WHEN typeof(`createdAt`) = 'real' THEN CAST(`createdAt` AS INTEGER) ELSE `createdAt` END, `updatedAt` = CASE WHEN typeof(`updatedAt`) = 'text' AND strftime('%s', `updatedAt`) IS NOT NULL THEN CAST(strftime('%s', `updatedAt`) AS INTEGER) * 1000 WHEN typeof(`updatedAt`) IN ('integer', 'real') AND abs(`updatedAt`) < 100000000000 THEN CAST(`updatedAt` * 1000 AS INTEGER) WHEN typeof(`updatedAt`) = 'real' THEN CAST(`updatedAt` AS INTEGER) ELSE `updatedAt` END;--> statement-breakpoint
UPDATE `Note` SET `createdAt` = CASE WHEN typeof(`createdAt`) = 'text' AND strftime('%s', `createdAt`) IS NOT NULL THEN CAST(strftime('%s', `createdAt`) AS INTEGER) * 1000 WHEN typeof(`createdAt`) IN ('integer', 'real') AND abs(`createdAt`) < 100000000000 THEN CAST(`createdAt` * 1000 AS INTEGER) WHEN typeof(`createdAt`) = 'real' THEN CAST(`createdAt` AS INTEGER) ELSE `createdAt` END, `updatedAt` = CASE WHEN typeof(`updatedAt`) = 'text' AND strftime('%s', `updatedAt`) IS NOT NULL THEN CAST(strftime('%s', `updatedAt`) AS INTEGER) * 1000 WHEN typeof(`updatedAt`) IN ('integer', 'real') AND abs(`updatedAt`) < 100000000000 THEN CAST(`updatedAt` * 1000 AS INTEGER) WHEN typeof(`updatedAt`) = 'real' THEN CAST(`updatedAt` AS INTEGER) ELSE `updatedAt` END;--> statement-breakpoint
UPDATE `Place` SET `createdAt` = CASE WHEN typeof(`createdAt`) = 'text' AND strftime('%s', `createdAt`) IS NOT NULL THEN CAST(strftime('%s', `createdAt`) AS INTEGER) * 1000 WHEN typeof(`createdAt`) IN ('integer', 'real') AND abs(`createdAt`) < 100000000000 THEN CAST(`createdAt` * 1000 AS INTEGER) WHEN typeof(`createdAt`) = 'real' THEN CAST(`createdAt` AS INTEGER) ELSE `createdAt` END, `updatedAt` = CASE WHEN typeof(`updatedAt`) = 'text' AND strftime('%s', `updatedAt`) IS NOT NULL THEN CAST(strftime('%s', `updatedAt`) AS INTEGER) * 1000 WHEN typeof(`updatedAt`) IN ('integer', 'real') AND abs(`updatedAt`) < 100000000000 THEN CAST(`updatedAt` * 1000 AS INTEGER) WHEN typeof(`updatedAt`) = 'real' THEN CAST(`updatedAt` AS INTEGER) ELSE `updatedAt` END;--> statement-breakpoint
UPDATE `Profile` SET `createdAt` = CASE WHEN typeof(`createdAt`) = 'text' AND strftime('%s', `createdAt`) IS NOT NULL THEN CAST(strftime('%s', `createdAt`) AS INTEGER) * 1000 WHEN typeof(`createdAt`) IN ('integer', 'real') AND abs(`createdAt`) < 100000000000 THEN CAST(`createdAt` * 1000 AS INTEGER) WHEN typeof(`createdAt`) = 'real' THEN CAST(`createdAt` AS INTEGER) ELSE `createdAt` END, `updatedAt` = CASE WHEN typeof(`updatedAt`) = 'text' AND strftime('%s', `updatedAt`) IS NOT NULL THEN CAST(strftime('%s', `updatedAt`) AS INTEGER) * 1000 WHEN typeof(`updatedAt`) IN ('integer', 'real') AND abs(`updatedAt`) < 100000000000 THEN CAST(`updatedAt` * 1000 AS INTEGER) WHEN typeof(`updatedAt`) = 'real' THEN CAST(`updatedAt` AS INTEGER) ELSE `updatedAt` END;--> statement-breakpoint
UPDATE `Prompt` SET `createdAt` = CASE WHEN typeof(`createdAt`) = 'text' AND strftime('%s', `createdAt`) IS NOT NULL THEN CAST(strftime('%s', `createdAt`) AS INTEGER) * 1000 WHEN typeof(`createdAt`) IN ('integer', 'real') AND abs(`createdAt`) < 100000000000 THEN CAST(`createdAt` * 1000 AS INTEGER) WHEN typeof(`createdAt`) = 'real' THEN CAST(`createdAt` AS INTEGER) ELSE `createdAt` END, `updatedAt` = CASE WHEN typeof(`updatedAt`) = 'text' AND strftime('%s', `updatedAt`) IS NOT NULL THEN CAST(strftime('%s', `updatedAt`) AS INTEGER) * 1000 WHEN typeof(`updatedAt`) IN ('integer', 'real') AND abs(`updatedAt`) < 100000000000 THEN CAST(`updatedAt` * 1000 AS INTEGER) WHEN typeof(`updatedAt`) = 'real' THEN CAST(`updatedAt` AS INTEGER) ELSE `updatedAt` END;--> statement-breakpoint
UPDATE `Property` SET `createdAt` = CASE WHEN typeof(`createdAt`) = 'text' AND strftime('%s', `createdAt`) IS NOT NULL THEN CAST(strftime('%s', `createdAt`) AS INTEGER) * 1000 WHEN typeof(`createdAt`) IN ('integer', 'real') AND abs(`createdAt`) < 100000000000 THEN CAST(`createdAt` * 1000 AS INTEGER) WHEN typeof(`createdAt`) = 'real' THEN CAST(`createdAt` AS INTEGER) ELSE `createdAt` END, `updatedAt` = CASE WHEN typeof(`updatedAt`) = 'text' AND strftime('%s', `updatedAt`) IS NOT NULL THEN CAST(strftime('%s', `updatedAt`) AS INTEGER) * 1000 WHEN typeof(`updatedAt`) IN ('integer', 'real') AND abs(`updatedAt`) < 100000000000 THEN CAST(`updatedAt` * 1000 AS INTEGER) WHEN typeof(`updatedAt`) = 'real' THEN CAST(`updatedAt` AS INTEGER) ELSE `updatedAt` END;--> statement-breakpoint
UPDATE `QueueJob` SET
	`startedAt` = CASE WHEN typeof(`startedAt`) = 'text' AND strftime('%s', `startedAt`) IS NOT NULL THEN CAST(strftime('%s', `startedAt`) AS INTEGER) * 1000 WHEN typeof(`startedAt`) IN ('integer', 'real') AND abs(`startedAt`) < 100000000000 THEN CAST(`startedAt` * 1000 AS INTEGER) WHEN typeof(`startedAt`) = 'real' THEN CAST(`startedAt` AS INTEGER) ELSE `startedAt` END,
	`finishedAt` = CASE WHEN typeof(`finishedAt`) = 'text' AND strftime('%s', `finishedAt`) IS NOT NULL THEN CAST(strftime('%s', `finishedAt`) AS INTEGER) * 1000 WHEN typeof(`finishedAt`) IN ('integer', 'real') AND abs(`finishedAt`) < 100000000000 THEN CAST(`finishedAt` * 1000 AS INTEGER) WHEN typeof(`finishedAt`) = 'real' THEN CAST(`finishedAt` AS INTEGER) ELSE `finishedAt` END,
	`createdAt` = CASE WHEN typeof(`createdAt`) = 'text' AND strftime('%s', `createdAt`) IS NOT NULL THEN CAST(strftime('%s', `createdAt`) AS INTEGER) * 1000 WHEN typeof(`createdAt`) IN ('integer', 'real') AND abs(`createdAt`) < 100000000000 THEN CAST(`createdAt` * 1000 AS INTEGER) WHEN typeof(`createdAt`) = 'real' THEN CAST(`createdAt` AS INTEGER) ELSE `createdAt` END,
	`updatedAt` = CASE WHEN typeof(`updatedAt`) = 'text' AND strftime('%s', `updatedAt`) IS NOT NULL THEN CAST(strftime('%s', `updatedAt`) AS INTEGER) * 1000 WHEN typeof(`updatedAt`) IN ('integer', 'real') AND abs(`updatedAt`) < 100000000000 THEN CAST(`updatedAt` * 1000 AS INTEGER) WHEN typeof(`updatedAt`) = 'real' THEN CAST(`updatedAt` AS INTEGER) ELSE `updatedAt` END,
	`retryAt` = CASE WHEN typeof(`retryAt`) = 'text' AND strftime('%s', `retryAt`) IS NOT NULL THEN CAST(strftime('%s', `retryAt`) AS INTEGER) * 1000 WHEN typeof(`retryAt`) IN ('integer', 'real') AND abs(`retryAt`) < 100000000000 THEN CAST(`retryAt` * 1000 AS INTEGER) WHEN typeof(`retryAt`) = 'real' THEN CAST(`retryAt` AS INTEGER) ELSE `retryAt` END;--> statement-breakpoint
UPDATE `Tag` SET `createdAt` = CASE WHEN typeof(`createdAt`) = 'text' AND strftime('%s', `createdAt`) IS NOT NULL THEN CAST(strftime('%s', `createdAt`) AS INTEGER) * 1000 WHEN typeof(`createdAt`) IN ('integer', 'real') AND abs(`createdAt`) < 100000000000 THEN CAST(`createdAt` * 1000 AS INTEGER) WHEN typeof(`createdAt`) = 'real' THEN CAST(`createdAt` AS INTEGER) ELSE `createdAt` END, `updatedAt` = CASE WHEN typeof(`updatedAt`) = 'text' AND strftime('%s', `updatedAt`) IS NOT NULL THEN CAST(strftime('%s', `updatedAt`) AS INTEGER) * 1000 WHEN typeof(`updatedAt`) IN ('integer', 'real') AND abs(`updatedAt`) < 100000000000 THEN CAST(`updatedAt` * 1000 AS INTEGER) WHEN typeof(`updatedAt`) = 'real' THEN CAST(`updatedAt` AS INTEGER) ELSE `updatedAt` END;--> statement-breakpoint
UPDATE `Thumbnail` SET `createdAt` = CASE WHEN typeof(`createdAt`) = 'text' AND strftime('%s', `createdAt`) IS NOT NULL THEN CAST(strftime('%s', `createdAt`) AS INTEGER) * 1000 WHEN typeof(`createdAt`) IN ('integer', 'real') AND abs(`createdAt`) < 100000000000 THEN CAST(`createdAt` * 1000 AS INTEGER) WHEN typeof(`createdAt`) = 'real' THEN CAST(`createdAt` AS INTEGER) ELSE `createdAt` END, `updatedAt` = CASE WHEN typeof(`updatedAt`) = 'text' AND strftime('%s', `updatedAt`) IS NOT NULL THEN CAST(strftime('%s', `updatedAt`) AS INTEGER) * 1000 WHEN typeof(`updatedAt`) IN ('integer', 'real') AND abs(`updatedAt`) < 100000000000 THEN CAST(`updatedAt` * 1000 AS INTEGER) WHEN typeof(`updatedAt`) = 'real' THEN CAST(`updatedAt` AS INTEGER) ELSE `updatedAt` END;--> statement-breakpoint
UPDATE `UploadedImage` SET `createdAt` = CASE WHEN typeof(`createdAt`) = 'text' AND strftime('%s', `createdAt`) IS NOT NULL THEN CAST(strftime('%s', `createdAt`) AS INTEGER) * 1000 WHEN typeof(`createdAt`) IN ('integer', 'real') AND abs(`createdAt`) < 100000000000 THEN CAST(`createdAt` * 1000 AS INTEGER) WHEN typeof(`createdAt`) = 'real' THEN CAST(`createdAt` AS INTEGER) ELSE `createdAt` END, `updatedAt` = CASE WHEN typeof(`updatedAt`) = 'text' AND strftime('%s', `updatedAt`) IS NOT NULL THEN CAST(strftime('%s', `updatedAt`) AS INTEGER) * 1000 WHEN typeof(`updatedAt`) IN ('integer', 'real') AND abs(`updatedAt`) < 100000000000 THEN CAST(`updatedAt` * 1000 AS INTEGER) WHEN typeof(`updatedAt`) = 'real' THEN CAST(`updatedAt` AS INTEGER) ELSE `updatedAt` END;--> statement-breakpoint
UPDATE `Video` SET `createdAt` = CASE WHEN typeof(`createdAt`) = 'text' AND strftime('%s', `createdAt`) IS NOT NULL THEN CAST(strftime('%s', `createdAt`) AS INTEGER) * 1000 WHEN typeof(`createdAt`) IN ('integer', 'real') AND abs(`createdAt`) < 100000000000 THEN CAST(`createdAt` * 1000 AS INTEGER) WHEN typeof(`createdAt`) = 'real' THEN CAST(`createdAt` AS INTEGER) ELSE `createdAt` END, `updatedAt` = CASE WHEN typeof(`updatedAt`) = 'text' AND strftime('%s', `updatedAt`) IS NOT NULL THEN CAST(strftime('%s', `updatedAt`) AS INTEGER) * 1000 WHEN typeof(`updatedAt`) IN ('integer', 'real') AND abs(`updatedAt`) < 100000000000 THEN CAST(`updatedAt` * 1000 AS INTEGER) WHEN typeof(`updatedAt`) = 'real' THEN CAST(`updatedAt` AS INTEGER) ELSE `updatedAt` END;--> statement-breakpoint
UPDATE `Wildcard` SET `createdAt` = CASE WHEN typeof(`createdAt`) = 'text' AND strftime('%s', `createdAt`) IS NOT NULL THEN CAST(strftime('%s', `createdAt`) AS INTEGER) * 1000 WHEN typeof(`createdAt`) IN ('integer', 'real') AND abs(`createdAt`) < 100000000000 THEN CAST(`createdAt` * 1000 AS INTEGER) WHEN typeof(`createdAt`) = 'real' THEN CAST(`createdAt` AS INTEGER) ELSE `createdAt` END, `updatedAt` = CASE WHEN typeof(`updatedAt`) = 'text' AND strftime('%s', `updatedAt`) IS NOT NULL THEN CAST(strftime('%s', `updatedAt`) AS INTEGER) * 1000 WHEN typeof(`updatedAt`) IN ('integer', 'real') AND abs(`updatedAt`) < 100000000000 THEN CAST(`updatedAt` * 1000 AS INTEGER) WHEN typeof(`updatedAt`) = 'real' THEN CAST(`updatedAt` AS INTEGER) ELSE `updatedAt` END;--> statement-breakpoint
UPDATE `WorldItem` SET `createdAt` = CASE WHEN typeof(`createdAt`) = 'text' AND strftime('%s', `createdAt`) IS NOT NULL THEN CAST(strftime('%s', `createdAt`) AS INTEGER) * 1000 WHEN typeof(`createdAt`) IN ('integer', 'real') AND abs(`createdAt`) < 100000000000 THEN CAST(`createdAt` * 1000 AS INTEGER) WHEN typeof(`createdAt`) = 'real' THEN CAST(`createdAt` AS INTEGER) ELSE `createdAt` END, `updatedAt` = CASE WHEN typeof(`updatedAt`) = 'text' AND strftime('%s', `updatedAt`) IS NOT NULL THEN CAST(strftime('%s', `updatedAt`) AS INTEGER) * 1000 WHEN typeof(`updatedAt`) IN ('integer', 'real') AND abs(`updatedAt`) < 100000000000 THEN CAST(`updatedAt` * 1000 AS INTEGER) WHEN typeof(`updatedAt`) = 'real' THEN CAST(`updatedAt` AS INTEGER) ELSE `updatedAt` END;--> statement-breakpoint

CREATE TEMP TABLE `__media_manager_epoch_validation` (`invalidCount` integer NOT NULL CHECK (`invalidCount` = 0));--> statement-breakpoint
INSERT INTO `__media_manager_epoch_validation` SELECT count(*) FROM `Activity` WHERE typeof(`createdAt`) <> 'integer';--> statement-breakpoint
INSERT INTO `__media_manager_epoch_validation` SELECT count(*) FROM `Album` WHERE (`lastImageAddedAt` IS NOT NULL AND typeof(`lastImageAddedAt`) <> 'integer') OR (`lastVideoAddedAt` IS NOT NULL AND typeof(`lastVideoAddedAt`) <> 'integer') OR typeof(`createdAt`) <> 'integer' OR (`updatedAt` IS NOT NULL AND typeof(`updatedAt`) <> 'integer');--> statement-breakpoint
INSERT INTO `__media_manager_epoch_validation` SELECT count(*) FROM `Audio` WHERE typeof(`createdAt`) <> 'integer' OR (`updatedAt` IS NOT NULL AND typeof(`updatedAt`) <> 'integer');--> statement-breakpoint
INSERT INTO `__media_manager_epoch_validation` SELECT count(*) FROM `Character` WHERE typeof(`createdAt`) <> 'integer' OR (`updatedAt` IS NOT NULL AND typeof(`updatedAt`) <> 'integer');--> statement-breakpoint
INSERT INTO `__media_manager_epoch_validation` SELECT count(*) FROM `Collection` WHERE (`lastImageAddedAt` IS NOT NULL AND typeof(`lastImageAddedAt`) <> 'integer') OR (`lastVideoAddedAt` IS NOT NULL AND typeof(`lastVideoAddedAt`) <> 'integer') OR typeof(`createdAt`) <> 'integer' OR (`updatedAt` IS NOT NULL AND typeof(`updatedAt`) <> 'integer');--> statement-breakpoint
INSERT INTO `__media_manager_epoch_validation` SELECT count(*) FROM `Concept` WHERE typeof(`createdAt`) <> 'integer' OR (`updatedAt` IS NOT NULL AND typeof(`updatedAt`) <> 'integer');--> statement-breakpoint
INSERT INTO `__media_manager_epoch_validation` SELECT count(*) FROM `Document` WHERE (`thumbnailErrorAt` IS NOT NULL AND typeof(`thumbnailErrorAt`) <> 'integer') OR (`creationDate` IS NOT NULL AND typeof(`creationDate`) <> 'integer') OR (`modificationDate` IS NOT NULL AND typeof(`modificationDate`) <> 'integer') OR typeof(`createdAt`) <> 'integer' OR (`updatedAt` IS NOT NULL AND typeof(`updatedAt`) <> 'integer');--> statement-breakpoint
INSERT INTO `__media_manager_epoch_validation` SELECT count(*) FROM `EntityAggregates` WHERE (`lastIndexed` IS NOT NULL AND typeof(`lastIndexed`) <> 'integer') OR (`updatedAt` IS NOT NULL AND typeof(`updatedAt`) <> 'integer');--> statement-breakpoint
INSERT INTO `__media_manager_epoch_validation` SELECT count(*) FROM `Favorite` WHERE typeof(`addedAt`) <> 'integer';--> statement-breakpoint
INSERT INTO `__media_manager_epoch_validation` SELECT count(*) FROM `File` WHERE (`lastAccessed` IS NOT NULL AND typeof(`lastAccessed`) <> 'integer') OR typeof(`createdAt`) <> 'integer' OR (`updatedAt` IS NOT NULL AND typeof(`updatedAt`) <> 'integer');--> statement-breakpoint
INSERT INTO `__media_manager_epoch_validation` SELECT count(*) FROM `File3D` WHERE typeof(`createdAt`) <> 'integer' OR (`updatedAt` IS NOT NULL AND typeof(`updatedAt`) <> 'integer');--> statement-breakpoint
INSERT INTO `__media_manager_epoch_validation` SELECT count(*) FROM `FileStats` WHERE typeof(`createdAt`) <> 'integer' OR (`updatedAt` IS NOT NULL AND typeof(`updatedAt`) <> 'integer');--> statement-breakpoint
INSERT INTO `__media_manager_epoch_validation` SELECT count(*) FROM `Folder` WHERE (`lastIndexed` IS NOT NULL AND typeof(`lastIndexed`) <> 'integer') OR typeof(`createdAt`) <> 'integer' OR (`updatedAt` IS NOT NULL AND typeof(`updatedAt`) <> 'integer');--> statement-breakpoint
INSERT INTO `__media_manager_epoch_validation` SELECT count(*) FROM `Group` WHERE typeof(`createdAt`) <> 'integer' OR (`updatedAt` IS NOT NULL AND typeof(`updatedAt`) <> 'integer');--> statement-breakpoint
INSERT INTO `__media_manager_epoch_validation` SELECT count(*) FROM `Image` WHERE (`thumbnailErrorAt` IS NOT NULL AND typeof(`thumbnailErrorAt`) <> 'integer') OR (`thumbnailOptimizedAt` IS NOT NULL AND typeof(`thumbnailOptimizedAt`) <> 'integer') OR typeof(`createdAt`) <> 'integer' OR (`updatedAt` IS NOT NULL AND typeof(`updatedAt`) <> 'integer') OR typeof(`addedAt`) <> 'integer';--> statement-breakpoint
INSERT INTO `__media_manager_epoch_validation` SELECT count(*) FROM `JsonFile` WHERE typeof(`createdAt`) <> 'integer' OR (`updatedAt` IS NOT NULL AND typeof(`updatedAt`) <> 'integer');--> statement-breakpoint
INSERT INTO `__media_manager_epoch_validation` SELECT count(*) FROM `Metadata` WHERE typeof(`createdAt`) <> 'integer' OR (`updatedAt` IS NOT NULL AND typeof(`updatedAt`) <> 'integer');--> statement-breakpoint
INSERT INTO `__media_manager_epoch_validation` SELECT count(*) FROM `Note` WHERE typeof(`createdAt`) <> 'integer' OR (`updatedAt` IS NOT NULL AND typeof(`updatedAt`) <> 'integer');--> statement-breakpoint
INSERT INTO `__media_manager_epoch_validation` SELECT count(*) FROM `Place` WHERE typeof(`createdAt`) <> 'integer' OR (`updatedAt` IS NOT NULL AND typeof(`updatedAt`) <> 'integer');--> statement-breakpoint
INSERT INTO `__media_manager_epoch_validation` SELECT count(*) FROM `Profile` WHERE typeof(`createdAt`) <> 'integer' OR (`updatedAt` IS NOT NULL AND typeof(`updatedAt`) <> 'integer');--> statement-breakpoint
INSERT INTO `__media_manager_epoch_validation` SELECT count(*) FROM `Prompt` WHERE typeof(`createdAt`) <> 'integer' OR (`updatedAt` IS NOT NULL AND typeof(`updatedAt`) <> 'integer');--> statement-breakpoint
INSERT INTO `__media_manager_epoch_validation` SELECT count(*) FROM `Property` WHERE typeof(`createdAt`) <> 'integer' OR (`updatedAt` IS NOT NULL AND typeof(`updatedAt`) <> 'integer');--> statement-breakpoint
INSERT INTO `__media_manager_epoch_validation` SELECT count(*) FROM `QueueJob` WHERE (`startedAt` IS NOT NULL AND typeof(`startedAt`) <> 'integer') OR (`finishedAt` IS NOT NULL AND typeof(`finishedAt`) <> 'integer') OR typeof(`createdAt`) <> 'integer' OR (`updatedAt` IS NOT NULL AND typeof(`updatedAt`) <> 'integer') OR (`retryAt` IS NOT NULL AND typeof(`retryAt`) <> 'integer');--> statement-breakpoint
INSERT INTO `__media_manager_epoch_validation` SELECT count(*) FROM `Tag` WHERE typeof(`createdAt`) <> 'integer' OR (`updatedAt` IS NOT NULL AND typeof(`updatedAt`) <> 'integer');--> statement-breakpoint
INSERT INTO `__media_manager_epoch_validation` SELECT count(*) FROM `Thumbnail` WHERE typeof(`createdAt`) <> 'integer' OR (`updatedAt` IS NOT NULL AND typeof(`updatedAt`) <> 'integer');--> statement-breakpoint
INSERT INTO `__media_manager_epoch_validation` SELECT count(*) FROM `UploadedImage` WHERE typeof(`createdAt`) <> 'integer' OR (`updatedAt` IS NOT NULL AND typeof(`updatedAt`) <> 'integer');--> statement-breakpoint
INSERT INTO `__media_manager_epoch_validation` SELECT count(*) FROM `Video` WHERE typeof(`createdAt`) <> 'integer' OR (`updatedAt` IS NOT NULL AND typeof(`updatedAt`) <> 'integer');--> statement-breakpoint
INSERT INTO `__media_manager_epoch_validation` SELECT count(*) FROM `Wildcard` WHERE typeof(`createdAt`) <> 'integer' OR (`updatedAt` IS NOT NULL AND typeof(`updatedAt`) <> 'integer');--> statement-breakpoint
INSERT INTO `__media_manager_epoch_validation` SELECT count(*) FROM `WorldItem` WHERE typeof(`createdAt`) <> 'integer' OR (`updatedAt` IS NOT NULL AND typeof(`updatedAt`) <> 'integer');--> statement-breakpoint
DROP TABLE `__media_manager_epoch_validation`;
